#### Gráficos de comparação de frequência de palavras por diretorias (2 a 2)
`COM STOPWORDS`

É importante ressaltar que os gráficos a seguir mostram, apenas, a comparação de frequência de palavras existentes em ambas diretorias. Ou seja, palavras existentes em apenas uma diretoria serão desconsideradas para a geração destes.

```{r}
PROP_PALAVRA = diretoria_palavras_noSTOP %>%
    #mutate(palavra = str_extract(palavra, "[a-z']+")) %>%
    mutate(proportion = n / sum(n)) %>%
    select(-n) %>%
    spread(DIRETORIA, proportion)
```


- DEE X DEA
```{r}
freq00 <- PROP_PALAVRA %>%
    gather(DIRETORIA, proportion, c(`DEA`))
  
  library(scales)
  # expect a warning about rows with missing values being removed
  ggplot(freq00, aes(x = proportion, y = `DEE`,
                        color = abs(`DEE` - proportion))) +
    geom_abline(color = "gray40", lty = 2) +
    geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) +
    geom_text(aes(label = palavra), check_overlap = TRUE, vjust = 1.5) +
    scale_x_log10(labels = percent_format(big.mark = ".", decimal.mark = ",", 
                                          accuracy = 1), limits = c(NA, 0.01)) +
    scale_y_log10(labels = percent_format(big.mark = ".", decimal.mark = ",", 
                                          accuracy = 1), limits = c(NA, 0.01)) +
    scale_color_gradient(limits = c(0, 0.001),
                         low = "darkslategray4", high = "gray75") +
    facet_wrap(~DIRETORIA, ncol = 1) +
    theme(legend.position="none") +
    labs(y = "DEE", x = NULL)
```

```{r}
cor.test(data = freq00[freq00$DIRETORIA == "DEA",],
             ~ proportion + `DEE`)
```

- DEE X OUTROS
```{r}
freq03 <- PROP_PALAVRA %>%
    gather(DIRETORIA, proportion, c(`OUTROS`))
  
  library(scales)
  # expect a warning about rows with missing values being removed
  ggplot(freq03, aes(x = proportion, y = `DEE`,
                        color = abs(`DEE` - proportion))) +
    geom_abline(color = "gray40", lty = 2) +
    geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) +
    geom_text(aes(label = palavra), check_overlap = TRUE, vjust = 1.5) +
    scale_x_log10(labels = percent_format(big.mark = ".", decimal.mark = ",", 
                                          accuracy = 1), limits = c(NA, 0.01)) +
    scale_y_log10(labels = percent_format(big.mark = ".", decimal.mark = ",", 
                                          accuracy = 1), limits = c(NA, 0.01)) +
    scale_color_gradient(limits = c(0, 0.001),
                         low = "darkslategray4", high = "gray75") +
    facet_wrap(~DIRETORIA, ncol = 1) +
    theme(legend.position="none") +
    labs(y = "DEE", x = NULL)
```

```{r}
cor.test(data = freq03[freq03$DIRETORIA == "OUTROS",],
             ~ proportion + `DEE`)
```

```yaml
Warning messages:
1: Removed 4273 rows containing missing values (geom_point). 
2: Removed 4274 rows containing missing values (geom_text).
```

- DEA X OUTROS
```{r}
freq06 <- PROP_PALAVRA %>%
    gather(DIRETORIA, proportion, c(`OUTROS`))
  
  library(scales)
  # expect a warning about rows with missing values being removed
  ggplot(freq06, aes(x = proportion, y = `DEA`,
                        color = abs(`DEA` - proportion))) +
    geom_abline(color = "gray40", lty = 2) +
    geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) +
    geom_text(aes(label = palavra), check_overlap = TRUE, vjust = 1.5) +
    scale_x_log10(labels = percent_format(big.mark = ".", decimal.mark = ",", 
                                          accuracy = 1), limits = c(NA, 0.01)) +
    scale_y_log10(labels = percent_format(big.mark = ".", decimal.mark = ",", 
                                          accuracy = 1), limits = c(NA, 0.01)) +
    scale_color_gradient(limits = c(0, 0.001),
                         low = "darkslategray4", high = "gray75") +
    facet_wrap(~DIRETORIA, ncol = 1) +
    theme(legend.position="none") +
    labs(y = "DEA", x = NULL)
```

```yaml
Warning messages:
1: Removed 4303 rows containing missing values (geom_point). 
2: Removed 4304 rows containing missing values (geom_text). 
```

```{r}
cor.test(data = freq06[freq06$DIRETORIA == "OUTROS",],
             ~ proportion + `DEA`)
```

<!--
```yaml
DEE <- diretoria_palavras %>%
  filter(DIRETORIA == "DEE")

DEA <- diretoria_palavras %>%
  filter(DIRETORIA == "DEA")

DPG <- diretoria_palavras %>%
  filter(DIRETORIA == "DPG")

DGC <- diretoria_palavras %>%
  filter(DIRETORIA == "DGC")

OUTROS <- diretoria_palavras %>%
  filter(DIRETORIA == "OUTROS")

library(tidyr)
  freq01 <- bind_rows(mutate(DEE, DIRETORIA = "DEE"),
                         mutate(DEA, DIRETORIA = "DEA"),
                         mutate(DPG, DIRETORIA = "DPG"),
                         mutate(DGC, DIRETORIA = "DGC"),
                         mutate(OUTROS, DIRETORIA = "OUTROS")) %>%
    mutate(palavra = str_extract(palavra, "[a-z']+")) %>%
    count(DIRETORIA, palavra) %>%
    group_by(DIRETORIA) %>%
    mutate(proportion = n / sum(n)) %>%
    select(-n) %>%
    spread(DIRETORIA, proportion) %>%
    gather(DIRETORIA, proportion, c(`DEE`,`DEA`,`DPG`,`DGC`))
  
  library(scales)
  # expect a warning about rows with missing values being removed
  ggplot(freq01, aes(x = proportion, y = `OUTROS`,
                        color = abs(`OUTROS` - proportion))) +
    geom_abline(color = "gray40", lty = 2) +
    geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) +
    geom_text(aes(label = palavra), check_overlap = TRUE, vjust = 1.5) +
    scale_x_log10(labels = percent_format(big.mark = ".", decimal.mark = ",")) +
    scale_y_log10(labels = percent_format(big.mark = ".", decimal.mark = ",")) +
    scale_color_gradient(limits = c(0, 0.001),
                         low = "darkslategray4", high = "gray75") +
    facet_wrap(~DIRETORIA, ncol = 4) +
    theme(legend.position="none") +
    labs(y = "OUTROS", x = NULL)
```
-->



<!--
```{r}
palavras_diretoria_DEE <- DB %>%
  select(DIRETORIA, DESCRI_PEDIDO) %>%
  filter(DIRETORIA == "DEE") %>%
  unnest_tokens(palavra, DESCRI_PEDIDO) 
  #count(DIRETORIA,palavra, sort = TRUE) %>%
  #ungroup() %>%  droplevels() %>% drop_na()

palavras_diretoria_DEA <- DB %>%
  select(DIRETORIA, DESCRI_PEDIDO) %>%
  filter(DIRETORIA == "DEA") %>%
  unnest_tokens(palavra, DESCRI_PEDIDO) 
  #count(DIRETORIA,palavra, sort = TRUE) %>%
  #ungroup() %>%  droplevels() %>% drop_na()

palavras_diretoria_OUTROS <- DB %>%
  select(DIRETORIA, DESCRI_PEDIDO) %>%
  filter(DIRETORIA == "OUTROS") %>%
  unnest_tokens(palavra, DESCRI_PEDIDO)
  #count(DIRETORIA,palavra, sort = TRUE) %>%
  #ungroup() %>%  droplevels() %>% drop_na()
```
-->