\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Mineração de texto aplicada à Lei de Acesso à informação - LAI},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Mineração de texto aplicada à Lei de Acesso à informação - LAI}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\begin{document}
\maketitle

\subsection{Packages for this routine}\label{packages-for-this-routine}

\section{BASE DE DADOS E ANÁLISE
EXPLORATÓRIA}\label{base-de-dados-e-analise-exploratoria}

\subsection{Importação dos dados}\label{importacao-dos-dados}

Caminho do projeto

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PATH = }\StringTok{"..;/proj_eSIC_v10/textmining_pt/DATA/"}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Pedidos e-SIC
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{FILE =}\StringTok{ "/DATA/relatorio_pedidos.ods"}
\NormalTok{db_raw =}\StringTok{ }\NormalTok{readODS}\OperatorTok{::}\KeywordTok{read.ods}\NormalTok{(}\DataTypeTok{file =} \KeywordTok{paste0}\NormalTok{(PATH,FILE), }\DataTypeTok{sheet =} \DecValTok{1}\NormalTok{); }\CommentTok{# dim(db_raw)}
\NormalTok{dbnames =}\StringTok{ }\NormalTok{db_raw[}\DecValTok{1}\NormalTok{,]; db_raw =}\StringTok{ }\NormalTok{db_raw[}\OperatorTok{-}\DecValTok{1}\NormalTok{,]; }
\KeywordTok{colnames}\NormalTok{(db_raw) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"ID"}\NormalTok{, }\StringTok{"DataRegistro"}\NormalTok{, }\StringTok{"DATA_PRAZOATEND"}\NormalTok{, }\StringTok{"DESCRI_PEDIDO"}\NormalTok{,}
                     \StringTok{"RESUMO_PEDIDO"}\NormalTok{, }\StringTok{"DATA_RESPOSTA"}\NormalTok{)}
\CommentTok{#View(head(db_raw))}
\NormalTok{LAI =}\StringTok{ }\NormalTok{db_raw}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Respostas e-SIC (DIRETORIAS EPE)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{FILE1 =}\StringTok{ "DATA/relatorio_respostas.xlsx"}
\NormalTok{db1_raw =}\StringTok{ }\NormalTok{readxl}\OperatorTok{::}\KeywordTok{read_excel}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(PATH,FILE1), }\DataTypeTok{sheet =} \StringTok{"DADOS"}\NormalTok{, }\DataTypeTok{col_names =} \OtherTok{TRUE}\NormalTok{); }
\CommentTok{# dim(db1_raw); names(db1_raw)}
\KeywordTok{colnames}\NormalTok{(db1_raw) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"ID"}\NormalTok{, }\StringTok{"DATA"}\NormalTok{, }\StringTok{"SOLICITACAO"}\NormalTok{, }\StringTok{"DIRETORIA"}\NormalTok{, }\StringTok{"DATA_RESPOSTA"}\NormalTok{)}
\CommentTok{#View(head(db1_raw))}
\NormalTok{LAI1 =}\StringTok{ }\NormalTok{db1_raw}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Stopwords
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{FILE2 =}\StringTok{ "DATA/stopwords_PT_FINAL.csv"}
\NormalTok{stopwords_pt =}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(PATH,FILE2), }\DataTypeTok{sep =} \StringTok{';'}\NormalTok{, }\DataTypeTok{header =}\NormalTok{ F, }\DataTypeTok{encoding =} \StringTok{"UTF-8"}\NormalTok{)}
\NormalTok{stopwords_pt =}\StringTok{ }\NormalTok{stopwords_pt[,}\OperatorTok{-}\DecValTok{2}\NormalTok{]; }
\KeywordTok{cat}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(}\StringTok{"O nosso vetor de stopwords contém "}\NormalTok{,}\KeywordTok{length}\NormalTok{(stopwords_pt), }\StringTok{" palavras únicas"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## O nosso vetor de stopwords contém 618 palavras únicas
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## dim(stopwords_pt); class(stopwords_pt)}
\NormalTok{stopwords_pt =}\StringTok{ }\KeywordTok{as.character}\NormalTok{(stopwords_pt)}
\NormalTok{stopwords_pt[}\DecValTok{1}\OperatorTok{:}\DecValTok{14}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "a"       "à"       "acerca"  "acesso"  "adeus"   "agora"   "aí"     
##  [8] "ainda"   "alem"    "além"    "algmas"  "algo"    "algumas" "alguns"
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Dicionário \textgreater{} BASE DE DADOS - REAL PRO TEXTO DO TCC
\end{itemize}

Dicionário de variáveis - PEDIDOS

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dicionario =}\StringTok{ "DATA/Dicionario-Dados-Exportacao.txt"}
\NormalTok{dic_pedidos =}\StringTok{ }\KeywordTok{read.delim}\NormalTok{(dicionario, }\DataTypeTok{sep =} \StringTok{"-"}\NormalTok{, }\DataTypeTok{skip =} \DecValTok{3}\NormalTok{, }\DataTypeTok{header =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{nrows =} \DecValTok{21}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{V1)}
\KeywordTok{colnames}\NormalTok{(dic_pedidos) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Nome das variáveis"}\NormalTok{, }\StringTok{"Tipo e descrição da variável"}\NormalTok{)}
\CommentTok{#dimnames(dic_pedidos); View(dic_pedidos)}
\end{Highlighting}
\end{Shaded}

Dicionário de variáveis - RECURSOS

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dic_recursos =}\StringTok{ }\KeywordTok{read.delim}\NormalTok{(dicionario, }\DataTypeTok{sep =} \StringTok{"-"}\NormalTok{, }\DataTypeTok{skip =} \DecValTok{30}\NormalTok{, }\DataTypeTok{header =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{nrows =} \DecValTok{17}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{V1)}
\KeywordTok{colnames}\NormalTok{(dic_recursos) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Nome das variáveis"}\NormalTok{, }\StringTok{"Tipo e descrição da variável"}\NormalTok{)}
\CommentTok{#dimnames(dic_recursos); View(dic_recursos)}
\end{Highlighting}
\end{Shaded}

Dicionário de variáveis - SOLICITANTES

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dicionario =}\StringTok{ "DATA/Dicionario-Dados-Exportacao.txt"}
\NormalTok{dic_solicitantes =}\StringTok{ }\KeywordTok{read.delim}\NormalTok{(}\DataTypeTok{file =}\NormalTok{ dicionario, }\DataTypeTok{sep =} \StringTok{"-"}\NormalTok{, }\DataTypeTok{skip =} \DecValTok{53}\NormalTok{, }\DataTypeTok{header =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{nrows =} \DecValTok{10}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{V1)}
\KeywordTok{colnames}\NormalTok{(dic_solicitantes) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Nome das variáveis"}\NormalTok{, }\StringTok{"Tipo e descrição da variável"}\NormalTok{)}
\CommentTok{#dimnames(dic_solicitantes); View(dic_solicitantes)}
\end{Highlighting}
\end{Shaded}

\subsection{Pré-processamento dos
dados}\label{pre-processamento-dos-dados}

\subsubsection{Pedidos por diretoria}\label{pedidos-por-diretoria}

\begin{itemize}
\tightlist
\item
  Tabela 01 número de solcitações/pedidos de informação
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAI1 }\OperatorTok{%>%}
\StringTok{ }\KeywordTok{count}\NormalTok{(DIRETORIA, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{name =} \StringTok{"total_pedidos"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable}\NormalTok{(}\StringTok{"latex"}\NormalTok{, }\DataTypeTok{caption =} \StringTok{"Quantitativo de solicitações por Diretoria/EPE via e-SIC"}\NormalTok{,}
        \DataTypeTok{booktabs =}\NormalTok{ T) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{latex_options =} \KeywordTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold_position"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-13}Quantitativo de solicitações por Diretoria/EPE via e-SIC}
\centering
\begin{tabular}{lr}
\toprule
DIRETORIA & total\_pedidos\\
\midrule
\rowcolor{gray!6}  DEA & 210\\
DEE & 197\\
\rowcolor{gray!6}  DGC & 115\\
DPG & 24\\
\rowcolor{gray!6}  OUTROS & 19\\
\addlinespace
SIC & 1\\
\bottomrule
\end{tabular}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diretorias0 =}\StringTok{ }\KeywordTok{levels}\NormalTok{(}\KeywordTok{as.factor}\NormalTok{(LAI1}\OperatorTok{$}\NormalTok{DIRETORIA))}
\end{Highlighting}
\end{Shaded}

Verificamos a existência de 5 diretorias, sendo elas: \emph{DEA},
\emph{DEE}, \emph{DGC}, \emph{DPG}, \emph{SIC} e \emph{OUTROS}. Essa
última é devido a existência de informações solicitadas que não são de
competência direta de nenhuma das cinco diretorias, daí a necessidade de
uma última categoria \emph{OUTROS} para atender essas demandas.

A seguir, um passo importante de reclassificação será executado devido
ao número pequeno de solicitações para a diretoria \emph{SIC}. Apenas
uma solcitação existente no nosso banco de dados para essa diretoria.
Iremos, portanto, unificar essa demanda à categoria \emph{OUTROS}.

\begin{itemize}
\tightlist
\item
  Respostas e-SIC - Reclassificação Diretorias
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAI1 =}\StringTok{ }\NormalTok{LAI1 }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DIRETORIA =} \KeywordTok{ifelse}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ }\NormalTok{diretorias0[}\DecValTok{6}\NormalTok{],diretorias0[}\DecValTok{5}\NormalTok{],DIRETORIA))}
\NormalTok{diretorias =}\StringTok{ }\KeywordTok{levels}\NormalTok{(}\KeywordTok{as.factor}\NormalTok{(LAI1}\OperatorTok{$}\NormalTok{DIRETORIA))}
\CommentTok{#dim(LAI1)}
\CommentTok{#View(head(LAI1))}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Tabela 02 número de solcitações/pedidos de informação - após
  reclassificação
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pedidos_diretoria =}\StringTok{ }\NormalTok{LAI1 }\OperatorTok{%>%}
\StringTok{ }\KeywordTok{count}\NormalTok{(DIRETORIA, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{name =} \StringTok{"total_pedidos"}\NormalTok{) }
\NormalTok{pedidos_diretoria }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable}\NormalTok{(}\StringTok{"latex"}\NormalTok{, }\DataTypeTok{caption =} \StringTok{"Quantitativo de solicitações por Diretoria/EPE via e-SIC - após reclassificação"}\NormalTok{, }
        \DataTypeTok{booktabs =}\NormalTok{ T) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{latex_options =} \KeywordTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold_position"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-15}Quantitativo de solicitações por Diretoria/EPE via e-SIC - após reclassificação}
\centering
\begin{tabular}{lr}
\toprule
DIRETORIA & total\_pedidos\\
\midrule
\rowcolor{gray!6}  DEA & 210\\
DEE & 197\\
\rowcolor{gray!6}  DGC & 115\\
DPG & 24\\
\rowcolor{gray!6}  OUTROS & 20\\
\bottomrule
\end{tabular}
\end{table}

As constatações anteriores foram feitas apenas na base de dados
referente às respostas, donde temos a classificação das diretorias
responsáveis por responder cada uma das demandas. É necessário, agora,
unificar as bases de dados pertinentes a solicitações e respostas.

\subsubsection{Unificando as duas bases}\label{unificando-as-duas-bases}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAI =}\StringTok{ }\NormalTok{LAI }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DATA_RESPOSTA); }\CommentTok{#dim(LAI)}
\NormalTok{LAI1 =}\StringTok{ }\NormalTok{LAI1 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DATA); }\CommentTok{#dim(LAI1)}
\NormalTok{DB =}\StringTok{ }\KeywordTok{left_join}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ LAI, }\DataTypeTok{y =}\NormalTok{ LAI1, }\DataTypeTok{by =} \StringTok{"ID"}\NormalTok{)}
\CommentTok{#View(head(DB))}
\end{Highlighting}
\end{Shaded}

Ver Anexo 01 c/ amostra dos dados da tabela que serpá utilizada para
manipulação daqui pra frente.

\subsection{Mineração de texto}\label{mineracao-de-texto}

Iniciamos as manipulações utilizando recursos da função
\texttt{unnest\_tokens(\ )} do pacote \texttt{library(tidytext)} que nos
permite trabalhar com textos em um formato \texttt{tidy} que coloca uma
palavra por linha em uma única coluna, formando, assim,
\emph{termos/palavras} por linha. Utilizamos, também, ainda os recursos
do pacote \texttt{library(diplyr)} para, posteriormente, agrupar esses
termos por diretoria e calcular a frequência dos \emph{termos}.

\begin{itemize}
\tightlist
\item
  Palavras
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidytext)}
\NormalTok{palavras <-}\StringTok{ }\NormalTok{DB }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unnest_tokens}\NormalTok{(palavra, DESCRI_PEDIDO) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(palavra, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Tabela 03 Palavras mais frequentes no conjunto de solicitações por
  diretoria
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{palavras[}\DecValTok{0}\OperatorTok{:}\DecValTok{10}\NormalTok{,] }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable}\NormalTok{(}\StringTok{"latex"}\NormalTok{, }\DataTypeTok{caption =} \StringTok{"Principais palavras com stopwords"}\NormalTok{, }
        \DataTypeTok{booktabs =}\NormalTok{ T, }\DataTypeTok{format.args =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{decimal.mark =} \StringTok{','}\NormalTok{, }\DataTypeTok{big.mark =} \StringTok{"'"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{latex_options =} \KeywordTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold_position"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-19}Principais palavras com stopwords}
\centering
\begin{tabular}{lr}
\toprule
palavra & n\\
\midrule
\rowcolor{gray!6}  de & 3'038\\
a & 1'093\\
\rowcolor{gray!6}  e & 946\\
o & 775\\
\rowcolor{gray!6}  do & 679\\
\addlinespace
da & 670\\
\rowcolor{gray!6}  para & 576\\
em & 481\\
\rowcolor{gray!6}  que & 462\\
no & 461\\
\bottomrule
\end{tabular}
\end{table}

Verificamos que as 10 palavras mais frequentes em todos os pedidos
realizados são palavras sem acréscimo contextual para alcançar o
objetivo aqui proposto, pois não acrescentam nenhum sentido semântico,
são essas: preposições (de, da, do, para), conjunção (e) e artigos(o,a).

Citar o que é preoposição.

No passo seguinte iremos remover essas palavras, \emph{stopwords}, e
trabalhar apenas com palavras de sentido semântico relevante aos
subjetivos solicitados às diretorias, acrescentando assim maior
assertividade na classificação do nosso modelo, ainda a ser proposto no
capítulo (indicar capítulo).

\begin{itemize}
\tightlist
\item
  Palavras por diretoria
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidytext)}
\NormalTok{diretoria_palavras <-}\StringTok{ }\NormalTok{DB }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unnest_tokens}\NormalTok{(palavra, DESCRI_PEDIDO) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(DIRETORIA, palavra, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

A tabela a seguir mostra a frequência das 10 palavras de maior
ocorrência de todos os pedidos, agregadados por diretoria.

\begin{itemize}
\tightlist
\item
  Tabela 04 Palavras mais frequentes no conjunto de solicitações por
  diretoria
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diretoria_palavras[}\DecValTok{0}\OperatorTok{:}\DecValTok{10}\NormalTok{,] }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable}\NormalTok{(}\StringTok{"latex"}\NormalTok{, }\DataTypeTok{caption =} \StringTok{"Palavras mais frequentes no conjunto de solicitações"}\NormalTok{, }
        \DataTypeTok{booktabs =}\NormalTok{ T, }\DataTypeTok{format.args =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{decimal.mark =} \StringTok{','}\NormalTok{, }\DataTypeTok{big.mark =} \StringTok{"'"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{latex_options =} \KeywordTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold_position"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-21}Palavras mais frequentes no conjunto de solicitações}
\centering
\begin{tabular}{llr}
\toprule
DIRETORIA & palavra & n\\
\midrule
\rowcolor{gray!6}  DEA & de & 1'127\\
DEE & de & 979\\
\rowcolor{gray!6}  DGC & de & 736\\
DEE & a & 364\\
\rowcolor{gray!6}  DEA & a & 350\\
\addlinespace
DEA & e & 329\\
\rowcolor{gray!6}  DGC & a & 304\\
DEE & e & 273\\
\rowcolor{gray!6}  DGC & e & 266\\
DEA & o & 262\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  Total de palavras
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{total_palavras =}\StringTok{ }\NormalTok{diretoria_palavras }\OperatorTok{%>%}
\KeywordTok{group_by}\NormalTok{(DIRETORIA) }\OperatorTok{%>%}
\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{total_palavras =} \KeywordTok{sum}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Tabela 05 Total de palavras por diretoria
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{total_palavras }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable}\NormalTok{(}\StringTok{"latex"}\NormalTok{, }\DataTypeTok{caption =} \StringTok{"Palavras mais frequentes no conjunto de solicitações"}\NormalTok{, }
        \DataTypeTok{booktabs =}\NormalTok{ T, }\DataTypeTok{format.args =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{decimal.mark =} \StringTok{','}\NormalTok{, }\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{latex_options =} \KeywordTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold_position"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-23}Palavras mais frequentes no conjunto de solicitações}
\centering
\begin{tabular}{lr}
\toprule
DIRETORIA & total\_palavras\\
\midrule
\rowcolor{gray!6}  DEA & 14.079\\
DEE & 12.907\\
\rowcolor{gray!6}  DGC & 10.355\\
DPG & 1.434\\
\rowcolor{gray!6}  OUTROS & 1.022\\
\bottomrule
\end{tabular}
\end{table}

É importante ressaltar aqui, a diferença extrema entre o número de
palavras existente por diretoria, isso se dá devido ao número de pedidos
realizados por diretoria já constatado anteriormente. Temos 210
solicitações registradas para a DEA, 197 para a DEE, 115 para a DGC e,
apenas, 24 e 20 pedidos para a DPG e OUTROS, respectivamente.

Vamos, portanto, visualizar o número médio de palavras por pedido e
diretoria. Para isso, vamos pegar o total de palavras por diretoria e
dividir pelo total de pedidos por diretoria.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prop_palavras_pedido_dir =}\StringTok{ }\KeywordTok{left_join}\NormalTok{(pedidos_diretoria, }
\NormalTok{                                                total_palavras, }\DataTypeTok{by =} \StringTok{"DIRETORIA"}\NormalTok{)}
\NormalTok{prop_palavras_pedido_dir}\OperatorTok{$}\NormalTok{palavras_por_pedido =}\StringTok{ }\KeywordTok{round}\NormalTok{(prop_palavras_pedido_dir}\OperatorTok{$}\NormalTok{total_palavras }\OperatorTok{/}\StringTok{ }\NormalTok{prop_palavras_pedido_dir}\OperatorTok{$}\NormalTok{total_pedidos, }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Tabela 06 Número médio de palavras por pedido e diretoria
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prop_palavras_pedido_dir }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable}\NormalTok{(}\StringTok{"latex"}\NormalTok{, }\DataTypeTok{caption =} \StringTok{"Palavras mais frequentes no conjunto de solicitações"}\NormalTok{, }
        \DataTypeTok{booktabs =}\NormalTok{ T, }\DataTypeTok{format.args =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{decimal.mark =} \StringTok{','}\NormalTok{, }\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{latex_options =} \KeywordTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold_position"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-25}Palavras mais frequentes no conjunto de solicitações}
\centering
\begin{tabular}{lrrr}
\toprule
DIRETORIA & total\_pedidos & total\_palavras & palavras\_por\_pedido\\
\midrule
\rowcolor{gray!6}  DEA & 210 & 14.079 & 67,04\\
DEE & 197 & 12.907 & 65,52\\
\rowcolor{gray!6}  DGC & 115 & 10.355 & 90,04\\
DPG & 24 & 1.434 & 59,75\\
\rowcolor{gray!6}  OUTROS & 20 & 1.022 & 51,10\\
\bottomrule
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  Junta informações
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diretoria_palavras =}\StringTok{ }\KeywordTok{left_join}\NormalTok{(diretoria_palavras, total_palavras, }\DataTypeTok{by =} \StringTok{"DIRETORIA"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Distribuição do nº de palavras usadas em solicitações por diretoria
  (histograma)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\NormalTok{gcomma <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x) }\KeywordTok{format}\NormalTok{(x, }\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{scientific =} \OtherTok{FALSE}\NormalTok{) }

\KeywordTok{ggplot}\NormalTok{(diretoria_palavras, }\KeywordTok{aes}\NormalTok{(n}\OperatorTok{/}\NormalTok{total_palavras, }\DataTypeTok{fill =}\NormalTok{ DIRETORIA)) }\OperatorTok{+}
\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{binwidth =}\NormalTok{ .}\DecValTok{0085}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{xlim}\NormalTok{(}\OtherTok{NA}\NormalTok{, .}\DecValTok{025}\NormalTok{) }\OperatorTok{+}
\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{, }\DataTypeTok{scales =} \StringTok{"free_y"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{gcomma) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{scale_x_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{gcomma)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Scale for 'x' is already present. Adding another scale for 'x', which
## will replace the existing scale.
\end{verbatim}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-27-1.pdf}

\begin{itemize}
\tightlist
\item
  Palavras mais frequentes por diretoria
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROP_PALAVRA =}\StringTok{ }\NormalTok{diretoria_palavras }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{palavra =} \KeywordTok{str_extract}\NormalTok{(palavra, }\StringTok{"[a-z']+"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{count}\NormalTok{(DIRETORIA, palavra) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{group_by}\NormalTok{(DIRETORIA) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{proportion =}\NormalTok{ n }\OperatorTok{/}\StringTok{ }\KeywordTok{sum}\NormalTok{(n)) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{n) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{spread}\NormalTok{(DIRETORIA, proportion)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Zipf's law
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq_by_rank <-}\StringTok{ }\NormalTok{diretoria_palavras }\OperatorTok{%>%}
\KeywordTok{group_by}\NormalTok{(DIRETORIA) }\OperatorTok{%>%}
\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{ranque =} \KeywordTok{row_number}\NormalTok{(),}
\StringTok{`}\DataTypeTok{frequência de termos}\StringTok{`}\NormalTok{ =}\StringTok{ }\NormalTok{n}\OperatorTok{/}\NormalTok{total_palavras)}

\CommentTok{# Plot}
\NormalTok{freq_by_rank }\OperatorTok{%>%}
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(ranque, }\StringTok{`}\DataTypeTok{frequência de termos}\StringTok{`}\NormalTok{, }\DataTypeTok{color =}\NormalTok{ DIRETORIA)) }\OperatorTok{+}
\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{intercept =} \OperatorTok{-}\FloatTok{0.62}\NormalTok{, }\DataTypeTok{slope =} \OperatorTok{-}\FloatTok{1.1}\NormalTok{, }\DataTypeTok{color =} \StringTok{"gray50"}\NormalTok{, }\DataTypeTok{linetype =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}
\KeywordTok{geom_line}\NormalTok{(}\DataTypeTok{size =} \FloatTok{1.1}\NormalTok{, }\DataTypeTok{alpha =} \FloatTok{0.8}\NormalTok{, }\DataTypeTok{show.legend =} \OtherTok{TRUE}\NormalTok{) }\OperatorTok{+}
\KeywordTok{scale_x_log10}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{gcomma) }\OperatorTok{+}
\KeywordTok{scale_y_log10}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{gcomma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-30-1.pdf}

\paragraph{Frequência de palavras por
diretoria}\label{frequencia-de-palavras-por-diretoria}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diretoria_palavras <-}\StringTok{ }\NormalTok{DB }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unnest_tokens}\NormalTok{(palavra, DESCRI_PEDIDO) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(DIRETORIA, palavra, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}
\CommentTok{#diretoria_palavras}

\NormalTok{plot_diretoria_palavras <-}\StringTok{ }\NormalTok{diretoria_palavras }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{bind_tf_idf}\NormalTok{(palavra, DIRETORIA, n) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(tf_idf)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{palavra =} \KeywordTok{factor}\NormalTok{(palavra, }\DataTypeTok{levels =} \KeywordTok{rev}\NormalTok{(}\KeywordTok{unique}\NormalTok{(palavra)))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DIRETORIA =} \KeywordTok{factor}\NormalTok{(DIRETORIA, }\DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\StringTok{"DEA"}\NormalTok{,}
                                                  \StringTok{"DEE"}\NormalTok{,}
                                                  \StringTok{"DGC"}\NormalTok{,}
                                                  \StringTok{"DPG"}\NormalTok{,}
                                                  \StringTok{"OUTROS"}\NormalTok{)))}
\CommentTok{#View(head(plot_diretoria_palavras))}
\CommentTok{#jpeg("02_freq_palavras_dir.jpeg")}
\NormalTok{plot_diretoria_palavras }\OperatorTok{%>%}
\KeywordTok{group_by}\NormalTok{(DIRETORIA) }\OperatorTok{%>%}
\KeywordTok{top_n}\NormalTok{(}\DecValTok{10}\NormalTok{, tf_idf) }\OperatorTok{%>%}
\KeywordTok{ungroup}\NormalTok{() }\OperatorTok{%>%}
\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{palavra =} \KeywordTok{reorder}\NormalTok{(palavra, tf_idf)) }\OperatorTok{%>%}
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(palavra, tf_idf, }\DataTypeTok{fill =}\NormalTok{ DIRETORIA)) }\OperatorTok{+}
\KeywordTok{geom_col}\NormalTok{(}\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{, }\DataTypeTok{y =} \StringTok{"tf-idf"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{, }\DataTypeTok{scales =} \StringTok{"free"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{gcomma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/02_freq_palavras_dir-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#dev.off()}
\end{Highlighting}
\end{Shaded}

\paragraph{Filtrando um pedaço de
texto}\label{filtrando-um-pedaco-de-texto}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DB }\OperatorTok{%>%}
\KeywordTok{filter}\NormalTok{(}\KeywordTok{str_detect}\NormalTok{(DESCRI_PEDIDO, }\StringTok{"r0"}\NormalTok{)) }\OperatorTok{%>%}
\KeywordTok{select}\NormalTok{(DESCRI_PEDIDO) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{head}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 DESCRI_PEDIDO
## 1                                                                                                                                                                                                                                                                          Prezados,\n\nSolicitamos que o deck do Newave 22.6 utilizado para Revisão da Garantia Física de UHEs, conforme consta da Nota Técnica EPE-DEE-RE-097/2016-r0 da Empresa de Pesquisa Energética -  EPE, nos seja enviado para conhecimento, por gentileza.\n\nObrigada,\nGraziella.
## 2                                                                                                                                                                                                                                                                                                                                                                                                                                                        Gostaria de ter acesso à Nota Técnica EPE-DEE-RE-097/2016-r0, pois não a encontro disponível online.
## 3 Solicitamos para nossa análise cópias dos relatórios nºs EPE-DEE-RE-147/2008-r0 que trata dos ESTUDOS RELATIVOS AOS GRANDES APROVEITAMENTOS HIDRELÉTRICOS NA REGIÃO AMAZÔNICA – Análise do sistema de atendimento aos estados do Acre e Rondônia no período Pré-Madeira – dezembro de 2008 e do relatório nº RE-EPES–4.010/08, que trata do SISTEMA ACRE-RONDÔNIA R2 – Estudos de Transitórios Eletromagnéticos e Condutor Econômico das LTs 230 kV P.Velho – Abunã – Rio Branco – janeiro de 2009.\n\nAgradecemos breve retorno.\n\nAtt.\n\nMônica\n\n\n\n
## 4                                                                                                                                                                                                                                                                                                                                                                            Cópia do documento EPE-DEE-RE-083/2010-r0, “Estudo de Integração das Usinas Hidrelétricas Previstas para o Estado de Santa Catarina”, elaborado pela EPE em novembro de 2010. \n
## 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Solicito cópia da Nota Técnica EPE-DEE-RE-097/2016-r0
## 6                                                                                                                                                                                                                                                                                                                                                                                                          Bom dia, por gentileza gostaria ter acesso ao parecer técnico EPE-DEE-PT-051/2016-r0 e projeto alternativo apresentado pela tecnogera.\n\nObrigada
\end{verbatim}

Uma limpeza removendo palavras sem significado semântico
(\textbf{stopwords}) pode auxiliar o algoritmo a retornar palavras ainda
mais acertivas

\subsubsection{Stemming}\label{stemming}

Podemos diminuir redundâncias por parte do algoritmo ensinando-o a
compreender palavras que podem estar escritas de forma diferente mas que
em significado semântico são semelhantes. Para isso, analisamos o
radical de palavras com um mesmo prefixo mas com sufixos diferentes seja
por quisistos como gênero ou plural.

Exemplos:

leilão \(\propto\) leilões estado \(\propto\) estados região \(\propto\)
regiões

\texttt{Falta\ implementar}

Usando o pacote \texttt{ptstem}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ptstem)}
\KeywordTok{ptstem}\NormalTok{(DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO[}\DecValTok{227}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Sou funcionário da Simple Energy, empresa representante da UTE Manauara. Estou realizando um levantamento sobre o cadastro dessa usina nos órgãos competentes (Aneel/CCEE/ONS/EPE, etc). E, gostaria de receber a Nota Técnica que subsidiou a publicação da garantia física da usina, publicação pela Portaria MME nº 185, de 28 de dezembro de 2012."
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stemming1 =}\StringTok{ }\KeywordTok{ptstem}\NormalTok{(DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO)}
\CommentTok{#ptstem(diretoria_palavras$palavra)}
\end{Highlighting}
\end{Shaded}

\paragraph{Frequência de palavras por
diretoria}\label{frequencia-de-palavras-por-diretoria-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diretoria_palavras_stem1 <-}\StringTok{ }\NormalTok{DB }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DESCRI_PEDIDO =}\NormalTok{ stemming1) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unnest_tokens}\NormalTok{(palavra, DESCRI_PEDIDO) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(palavra, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cat}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(}\StringTok{"Utilizando o algoritmo de stemming do pacote 'ptstem' o número de palavras chaves sem stemming reduziu de "}\NormalTok{, }\KeywordTok{dim}\NormalTok{(diretoria_palavras)[}\DecValTok{1}\NormalTok{], }\StringTok{" para "}\NormalTok{, }\KeywordTok{dim}\NormalTok{(diretoria_palavras_stem1)[}\DecValTok{1}\NormalTok{], }\StringTok{", após stemming. Uma redução de "}\NormalTok{, }\KeywordTok{round}\NormalTok{(}\DecValTok{100}\OperatorTok{-}\KeywordTok{dim}\NormalTok{(diretoria_palavras_stem1)[}\DecValTok{1}\NormalTok{]}\OperatorTok{*}\DecValTok{100}\OperatorTok{/}\KeywordTok{dim}\NormalTok{(diretoria_palavras)[}\DecValTok{1}\NormalTok{],}\DecValTok{0}\NormalTok{),}\StringTok{"%."}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Utilizando o algoritmo de stemming do pacote 'ptstem' o número de palavras chaves sem stemming reduziu de 8629 para 3879, após stemming. Uma redução de 55%.
\end{verbatim}

Usando o pacote \texttt{rslp}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(rslp)}
\KeywordTok{rslp}\NormalTok{(DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO[}\DecValTok{227}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Sou funcionario da Simple Energy, empresa representante da UTE Manauara. Estou realizando um levantamento sobre o cadastro dessa usina nos orgaos competentes (Aneel/CCEE/ONS/EPE, etc). E, gostaria de receber a Nota Tecnica que subsidiou a publicacao da garantia fisica da usina, publicada pela Portaria MME nº 185, de 28 de dezembro de 2012."
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stemming2 =}\StringTok{ }\KeywordTok{rslp}\NormalTok{(DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO)}
\end{Highlighting}
\end{Shaded}

\paragraph{Frequência de palavras por
diretoria}\label{frequencia-de-palavras-por-diretoria-2}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diretoria_palavras_stem2 <-}\StringTok{ }\NormalTok{DB }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DESCRI_PEDIDO =}\NormalTok{ stemming2) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unnest_tokens}\NormalTok{(palavra, DESCRI_PEDIDO) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(palavra, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cat}\NormalTok{(}\KeywordTok{paste0}\NormalTok{(}\StringTok{"Utilizando o algoritmo de stemming do pacote 'rslp' o número de palavras chaves sem stemming reduziu de "}\NormalTok{, }\KeywordTok{dim}\NormalTok{(diretoria_palavras)[}\DecValTok{1}\NormalTok{], }\StringTok{" para "}\NormalTok{, }\KeywordTok{dim}\NormalTok{(diretoria_palavras_stem2)[}\DecValTok{1}\NormalTok{], }\StringTok{", após stemming. Uma redução de "}\NormalTok{, }\KeywordTok{round}\NormalTok{(}\DecValTok{100}\OperatorTok{-}\KeywordTok{dim}\NormalTok{(diretoria_palavras_stem2)[}\DecValTok{1}\NormalTok{]}\OperatorTok{*}\DecValTok{100}\OperatorTok{/}\KeywordTok{dim}\NormalTok{(diretoria_palavras)[}\DecValTok{1}\NormalTok{],}\DecValTok{0}\NormalTok{),}\StringTok{"%."}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Utilizando o algoritmo de stemming do pacote 'rslp' o número de palavras chaves sem stemming reduziu de 8629 para 5376, após stemming. Uma redução de 38%.
\end{verbatim}

Uma redução considerável no número de termos ocorreu ao usar o algoritmo
\texttt{ptstem}, cerca de 55\% de redução de termos versus 38\%
utilziando o algoritmo \texttt{rslp}.

Vale ressaltar, tabmbém, o tempo de processamento que ambos os
algoritmos requerem.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{temp_stem1 =}\StringTok{ }\KeywordTok{proc.time}\NormalTok{()}
\NormalTok{test0 =}\StringTok{ }\KeywordTok{ptstem}\NormalTok{(DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO)}
\NormalTok{tempo_stem1 =}\StringTok{ }\KeywordTok{proc.time}\NormalTok{() }\OperatorTok{-}\StringTok{ }\NormalTok{temp_stem1}
\KeywordTok{remove}\NormalTok{(teste0)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in remove(teste0): objeto 'teste0' não encontrado
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{temp_stem2 =}\StringTok{ }\KeywordTok{proc.time}\NormalTok{()}
\NormalTok{teste00 =}\StringTok{ }\KeywordTok{rslp}\NormalTok{(DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO)}
\NormalTok{tempo_stem2 =}\StringTok{ }\KeywordTok{proc.time}\NormalTok{() }\OperatorTok{-}\StringTok{ }\NormalTok{temp_stem2}
\KeywordTok{remove}\NormalTok{(teste00)}
\end{Highlighting}
\end{Shaded}

O tempo decorrido para processamento do algoritmo do \texttt{ptstem} foi
de aproximadamente 12,4 segundos versus 1,0 segundo decorrido para o
processamento do algoritmo do \texttt{rslp}. Logo, o \texttt{rslp} é
quase 13 vezes mais eficiente em termos de tempo de processamento. Além
disso, o \texttt{rslp} remove acentuações e caracteres como ``ç''. Isso
irá nos ajudar mais a frente quando utilizarmos os principais termos
como variáveis binárias e preditoras do modelo de classificação.

Entretanto, o algoritmo mais lento, \texttt{ptstem}, foi mais
interessante em termos de redução do número de termos únicos, cerca de
22\% menos termos em relação ao outro algoritmo. Além disso, por se
tratar de uma base de dados relativamente pequena, 565 pedidos, e o alto
poder de processamento da máquina utilizada para esse estudo.

Optamos, portanto, por utilizar ambos algoritmos. Vamos, primeiro,
aplicar o removedor de sufixos da lingua portuguesa \texttt{rslp}
seguido do \texttt{ptstem}.

\paragraph{Frequência de palavras por
diretoria}\label{frequencia-de-palavras-por-diretoria-3}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stemming3 =}\StringTok{ }\KeywordTok{ptstem}\NormalTok{(stemming2)}
\NormalTok{diretoria_palavras_stem3 <-}\StringTok{ }\NormalTok{DB }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DESCRI_PEDIDO =}\NormalTok{ stemming3) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unnest_tokens}\NormalTok{(palavra, DESCRI_PEDIDO) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(DIRETORIA, palavra, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}
\CommentTok{#diretoria_palavras}
\end{Highlighting}
\end{Shaded}

Vamos, agora, plotar as quinze palavras mais relevantes de acordo com a
estatística \textbf{tf\_idf}, por diretoria

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot_diretoria_palavras_stem <-}\StringTok{ }\NormalTok{diretoria_palavras_stem3 }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{bind_tf_idf}\NormalTok{(palavra, DIRETORIA, n) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(tf_idf)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{palavra =} \KeywordTok{factor}\NormalTok{(palavra, }\DataTypeTok{levels =} \KeywordTok{rev}\NormalTok{(}\KeywordTok{unique}\NormalTok{(palavra)))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DIRETORIA =} \KeywordTok{factor}\NormalTok{(DIRETORIA, }\DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\StringTok{"DEA"}\NormalTok{,}
                                                  \StringTok{"DEE"}\NormalTok{,}
                                                  \StringTok{"DGC"}\NormalTok{,}
                                                  \StringTok{"DPG"}\NormalTok{,}
                                                  \StringTok{"OUTROS"}\NormalTok{)))}
\CommentTok{#View(head(plot_diretoria_palavras))}
\CommentTok{#jpeg("02_freq_palavras_dir.jpeg")}
\NormalTok{plot_diretoria_palavras_stem }\OperatorTok{%>%}
\KeywordTok{group_by}\NormalTok{(DIRETORIA) }\OperatorTok{%>%}
\KeywordTok{top_n}\NormalTok{(}\DecValTok{15}\NormalTok{, tf_idf) }\OperatorTok{%>%}
\KeywordTok{ungroup}\NormalTok{() }\OperatorTok{%>%}
\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{palavra =} \KeywordTok{reorder}\NormalTok{(palavra, tf_idf)) }\OperatorTok{%>%}
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(palavra, tf_idf, }\DataTypeTok{fill =}\NormalTok{ DIRETORIA)) }\OperatorTok{+}
\KeywordTok{geom_col}\NormalTok{(}\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{, }\DataTypeTok{y =} \StringTok{"tf-idf"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{, }\DataTypeTok{scales =} \StringTok{"free"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{gcomma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-42-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#dev.off()}
\end{Highlighting}
\end{Shaded}

\subsubsection{Stopwords}\label{stopwords}

Com o arquivo de \texttt{stopwords}previamente inserido vamos,
primeiramente, transforma-lo em um data\_frame a fim de futuramente
utilizá-lo para extrair do texto palavras em comum.

\paragraph{\texorpdfstring{Freq. de palavras sem \textbf{stopwords} por
diretoria}{Freq. de palavras sem stopwords por diretoria}}\label{freq.-de-palavras-sem-stopwords-por-diretoria}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mystopwords <-}\StringTok{ }\KeywordTok{data_frame}\NormalTok{(}\DataTypeTok{palavra =}\NormalTok{ stopwords_pt)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: `data_frame()` is deprecated, use `tibble()`.
## This warning is displayed once per session.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diretoria_palavras_noSTOP <-}\StringTok{ }\KeywordTok{anti_join}\NormalTok{(diretoria_palavras_stem3, mystopwords, }\DataTypeTok{by =} \StringTok{"palavra"}\NormalTok{)}
\CommentTok{#View(head(diretoria_palavras_noSTOP))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#diretoria_palavras_noSTOP_noSTOP}
\NormalTok{plot_diretoria_palavras_noSTOP <-}\StringTok{ }\NormalTok{diretoria_palavras_noSTOP }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{bind_tf_idf}\NormalTok{(palavra, DIRETORIA, n) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(tf_idf)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{word =} \KeywordTok{factor}\NormalTok{(palavra, }\DataTypeTok{levels =} \KeywordTok{rev}\NormalTok{(}\KeywordTok{unique}\NormalTok{(palavra)))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DIRETORIA =} \KeywordTok{factor}\NormalTok{(DIRETORIA, }\DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\StringTok{"DEA"}\NormalTok{,}
                                                  \StringTok{"DEE"}\NormalTok{,}
                                                  \StringTok{"DGC"}\NormalTok{,}
                                                  \StringTok{"DPG"}\NormalTok{,}
                                                  \StringTok{"OUTROS"}\NormalTok{)))}
\CommentTok{#plot_diretoria_palavras_noSTOP}
\CommentTok{#windows.options(width=10, height=10)}
\CommentTok{#jpeg("03_freq_palavras_dir_nostop.jpeg")}
\NormalTok{plot_diretoria_palavras_noSTOP }\OperatorTok{%>%}
\KeywordTok{group_by}\NormalTok{(DIRETORIA) }\OperatorTok{%>%}
\KeywordTok{top_n}\NormalTok{(}\DecValTok{15}\NormalTok{, tf_idf) }\OperatorTok{%>%}
\KeywordTok{ungroup}\NormalTok{() }\OperatorTok{%>%}
\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{palavra =} \KeywordTok{reorder}\NormalTok{(palavra, tf_idf)) }\OperatorTok{%>%}
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(palavra, tf_idf, }\DataTypeTok{fill =}\NormalTok{ DIRETORIA)) }\OperatorTok{+}
\KeywordTok{geom_col}\NormalTok{(}\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{, }\DataTypeTok{y =} \StringTok{"tf-idf"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{, }\DataTypeTok{scales =} \StringTok{"free"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{gcomma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/03_freq_palavras_dir_nostop-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#dev.off()}
\end{Highlighting}
\end{Shaded}

\paragraph{Gráficos de comparação de frequência de palavras por
diretorias (2 a
2)}\label{graficos-de-comparacao-de-frequencia-de-palavras-por-diretorias-2-a-2}

\texttt{COM\ STOPWORDS}

É importante ressaltar que os gráficos a seguir mostram, apenas, a
comparação de frequência de palavras existentes em ambas diretorias. Ou
seja, palavras existentes em apenas uma diretoria serão desconsideradas
para a geração destes.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PROP_PALAVRA =}\StringTok{ }\NormalTok{diretoria_palavras_noSTOP }\OperatorTok{%>%}
\StringTok{    }\CommentTok{#mutate(palavra = str_extract(palavra, "[a-z']+")) %>%}
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{proportion =}\NormalTok{ n }\OperatorTok{/}\StringTok{ }\KeywordTok{sum}\NormalTok{(n)) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{n) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{spread}\NormalTok{(DIRETORIA, proportion)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  DEE X DEA
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq00 <-}\StringTok{ }\NormalTok{PROP_PALAVRA }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{gather}\NormalTok{(DIRETORIA, proportion, }\KeywordTok{c}\NormalTok{(}\StringTok{`}\DataTypeTok{DEA}\StringTok{`}\NormalTok{))}
  
  \KeywordTok{library}\NormalTok{(scales)}
  \CommentTok{# expect a warning about rows with missing values being removed}
  \KeywordTok{ggplot}\NormalTok{(freq00, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ proportion, }\DataTypeTok{y =} \StringTok{`}\DataTypeTok{DEE}\StringTok{`}\NormalTok{,}
                        \DataTypeTok{color =} \KeywordTok{abs}\NormalTok{(}\StringTok{`}\DataTypeTok{DEE}\StringTok{`} \OperatorTok{-}\StringTok{ }\NormalTok{proportion))) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{color =} \StringTok{"gray40"}\NormalTok{, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{width =} \FloatTok{0.3}\NormalTok{, }\DataTypeTok{height =} \FloatTok{0.3}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ palavra), }\DataTypeTok{check_overlap =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{vjust =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_x_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_y_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_color_gradient}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.001}\NormalTok{),}
                         \DataTypeTok{low =} \StringTok{"darkslategray4"}\NormalTok{, }\DataTypeTok{high =} \StringTok{"gray75"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{y =} \StringTok{"DEE"}\NormalTok{, }\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 2825 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 2823 rows containing missing values (geom_text).
\end{verbatim}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-53-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ freq00[freq00}\OperatorTok{$}\NormalTok{DIRETORIA }\OperatorTok{==}\StringTok{ "DEA"}\NormalTok{,],}
             \OperatorTok{~}\StringTok{ }\NormalTok{proportion }\OperatorTok{+}\StringTok{ `}\DataTypeTok{DEE}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  proportion and DEE
## t = 30.221, df = 890, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6776757 0.7426100
## sample estimates:
##       cor 
## 0.7116595
\end{verbatim}

\begin{itemize}
\tightlist
\item
  DEE X DPG
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq01 <-}\StringTok{ }\NormalTok{PROP_PALAVRA }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{gather}\NormalTok{(DIRETORIA, proportion, }\KeywordTok{c}\NormalTok{(}\StringTok{`}\DataTypeTok{DPG}\StringTok{`}\NormalTok{))}
  
  \KeywordTok{library}\NormalTok{(scales)}
  \CommentTok{# expect a warning about rows with missing values being removed}
  \KeywordTok{ggplot}\NormalTok{(freq01, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ proportion, }\DataTypeTok{y =} \StringTok{`}\DataTypeTok{DEE}\StringTok{`}\NormalTok{,}
                        \DataTypeTok{color =} \KeywordTok{abs}\NormalTok{(}\StringTok{`}\DataTypeTok{DEE}\StringTok{`} \OperatorTok{-}\StringTok{ }\NormalTok{proportion))) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{color =} \StringTok{"gray40"}\NormalTok{, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{width =} \FloatTok{0.3}\NormalTok{, }\DataTypeTok{height =} \FloatTok{0.3}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ palavra), }\DataTypeTok{check_overlap =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{vjust =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_x_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_y_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_color_gradient}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.001}\NormalTok{),}
                         \DataTypeTok{low =} \StringTok{"darkslategray4"}\NormalTok{, }\DataTypeTok{high =} \StringTok{"gray75"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{y =} \StringTok{"DEE"}\NormalTok{, }\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 3438 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 3438 rows containing missing values (geom_text).
\end{verbatim}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-55-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ freq01[freq01}\OperatorTok{$}\NormalTok{DIRETORIA }\OperatorTok{==}\StringTok{ "DPG"}\NormalTok{,],}
             \OperatorTok{~}\StringTok{ }\NormalTok{proportion }\OperatorTok{+}\StringTok{ `}\DataTypeTok{DEE}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  proportion and DEE
## t = 7.7037, df = 275, p-value = 2.406e-13
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.3193085 0.5136596
## sample estimates:
##       cor 
## 0.4213092
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Warning messages:}
\FunctionTok{1:}\AttributeTok{ Removed 4235 rows containing missing values (geom_point). }
\FunctionTok{2:}\AttributeTok{ Removed 4236 rows containing missing values (geom_text). }
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  DEE X DGC
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq02 <-}\StringTok{ }\NormalTok{PROP_PALAVRA }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{gather}\NormalTok{(DIRETORIA, proportion, }\KeywordTok{c}\NormalTok{(}\StringTok{`}\DataTypeTok{DGC}\StringTok{`}\NormalTok{))}
  
  \KeywordTok{library}\NormalTok{(scales)}
  \CommentTok{# expect a warning about rows with missing values being removed}
  \KeywordTok{ggplot}\NormalTok{(freq02, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ proportion, }\DataTypeTok{y =} \StringTok{`}\DataTypeTok{DEE}\StringTok{`}\NormalTok{,}
                        \DataTypeTok{color =} \KeywordTok{abs}\NormalTok{(}\StringTok{`}\DataTypeTok{DEE}\StringTok{`} \OperatorTok{-}\StringTok{ }\NormalTok{proportion))) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{color =} \StringTok{"gray40"}\NormalTok{, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{width =} \FloatTok{0.3}\NormalTok{, }\DataTypeTok{height =} \FloatTok{0.3}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ palavra), }\DataTypeTok{check_overlap =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{vjust =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_x_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_y_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_color_gradient}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.001}\NormalTok{),}
                         \DataTypeTok{low =} \StringTok{"darkslategray4"}\NormalTok{, }\DataTypeTok{high =} \StringTok{"gray75"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{y =} \StringTok{"DEE"}\NormalTok{, }\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 3075 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 3075 rows containing missing values (geom_text).
\end{verbatim}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-57-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ freq02[freq02}\OperatorTok{$}\NormalTok{DIRETORIA }\OperatorTok{==}\StringTok{ "DGC"}\NormalTok{,],}
             \OperatorTok{~}\StringTok{ }\NormalTok{proportion }\OperatorTok{+}\StringTok{ `}\DataTypeTok{DEE}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  proportion and DEE
## t = 10.85, df = 638, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.3271860 0.4581655
## sample estimates:
##      cor 
## 0.394679
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Warning messages:}
\FunctionTok{1:}\AttributeTok{ Removed 3794 rows containing missing values (geom_point). }
\FunctionTok{2:}\AttributeTok{ Removed 3795 rows containing missing values (geom_text).}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  DEE X OUTROS
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq03 <-}\StringTok{ }\NormalTok{PROP_PALAVRA }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{gather}\NormalTok{(DIRETORIA, proportion, }\KeywordTok{c}\NormalTok{(}\StringTok{`}\DataTypeTok{OUTROS}\StringTok{`}\NormalTok{))}
  
  \KeywordTok{library}\NormalTok{(scales)}
  \CommentTok{# expect a warning about rows with missing values being removed}
  \KeywordTok{ggplot}\NormalTok{(freq03, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ proportion, }\DataTypeTok{y =} \StringTok{`}\DataTypeTok{DEE}\StringTok{`}\NormalTok{,}
                        \DataTypeTok{color =} \KeywordTok{abs}\NormalTok{(}\StringTok{`}\DataTypeTok{DEE}\StringTok{`} \OperatorTok{-}\StringTok{ }\NormalTok{proportion))) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{color =} \StringTok{"gray40"}\NormalTok{, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{width =} \FloatTok{0.3}\NormalTok{, }\DataTypeTok{height =} \FloatTok{0.3}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ palavra), }\DataTypeTok{check_overlap =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{vjust =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_x_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_y_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_color_gradient}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.001}\NormalTok{),}
                         \DataTypeTok{low =} \StringTok{"darkslategray4"}\NormalTok{, }\DataTypeTok{high =} \StringTok{"gray75"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{y =} \StringTok{"DEE"}\NormalTok{, }\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 3477 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 3477 rows containing missing values (geom_text).
\end{verbatim}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-59-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ freq03[freq03}\OperatorTok{$}\NormalTok{DIRETORIA }\OperatorTok{==}\StringTok{ "OUTROS"}\NormalTok{,],}
             \OperatorTok{~}\StringTok{ }\NormalTok{proportion }\OperatorTok{+}\StringTok{ `}\DataTypeTok{DEE}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  proportion and DEE
## t = 12.789, df = 236, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.5580327 0.7092533
## sample estimates:
##       cor 
## 0.6397945
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Warning messages:}
\FunctionTok{1:}\AttributeTok{ Removed 4273 rows containing missing values (geom_point). }
\FunctionTok{2:}\AttributeTok{ Removed 4274 rows containing missing values (geom_text).}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  DEA X DPG
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq04 <-}\StringTok{ }\NormalTok{PROP_PALAVRA }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{gather}\NormalTok{(DIRETORIA, proportion, }\KeywordTok{c}\NormalTok{(}\StringTok{`}\DataTypeTok{DPG}\StringTok{`}\NormalTok{))}
  
  \KeywordTok{library}\NormalTok{(scales)}
  \CommentTok{# expect a warning about rows with missing values being removed}
  \KeywordTok{ggplot}\NormalTok{(freq04, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ proportion, }\DataTypeTok{y =} \StringTok{`}\DataTypeTok{DEA}\StringTok{`}\NormalTok{,}
                        \DataTypeTok{color =} \KeywordTok{abs}\NormalTok{(}\StringTok{`}\DataTypeTok{DEA}\StringTok{`} \OperatorTok{-}\StringTok{ }\NormalTok{proportion))) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{color =} \StringTok{"gray40"}\NormalTok{, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{width =} \FloatTok{0.3}\NormalTok{, }\DataTypeTok{height =} \FloatTok{0.3}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ palavra), }\DataTypeTok{check_overlap =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{vjust =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_x_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_y_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_color_gradient}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.001}\NormalTok{),}
                         \DataTypeTok{low =} \StringTok{"darkslategray4"}\NormalTok{, }\DataTypeTok{high =} \StringTok{"gray75"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{y =} \StringTok{"DEA"}\NormalTok{, }\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 3439 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 3437 rows containing missing values (geom_text).
\end{verbatim}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-61-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Warning messages:}
\FunctionTok{1:}\AttributeTok{ Removed 4221 rows containing missing values (geom_point). }
\FunctionTok{2:}\AttributeTok{ Removed 4222 rows containing missing values (geom_text).}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ freq04[freq04}\OperatorTok{$}\NormalTok{DIRETORIA }\OperatorTok{==}\StringTok{ "DPG"}\NormalTok{,],}
             \OperatorTok{~}\StringTok{ }\NormalTok{proportion }\OperatorTok{+}\StringTok{ `}\DataTypeTok{DEA}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  proportion and DEA
## t = 6.1072, df = 276, p-value = 3.432e-09
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.2370151 0.4446322
## sample estimates:
##       cor 
## 0.3450374
\end{verbatim}

\begin{itemize}
\tightlist
\item
  DEA X DGC
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq05 <-}\StringTok{ }\NormalTok{PROP_PALAVRA }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{gather}\NormalTok{(DIRETORIA, proportion, }\KeywordTok{c}\NormalTok{(}\StringTok{`}\DataTypeTok{DGC}\StringTok{`}\NormalTok{))}
  
  \KeywordTok{library}\NormalTok{(scales)}
  \CommentTok{# expect a warning about rows with missing values being removed}
  \KeywordTok{ggplot}\NormalTok{(freq05, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ proportion, }\DataTypeTok{y =} \StringTok{`}\DataTypeTok{DEA}\StringTok{`}\NormalTok{,}
                        \DataTypeTok{color =} \KeywordTok{abs}\NormalTok{(}\StringTok{`}\DataTypeTok{DEA}\StringTok{`} \OperatorTok{-}\StringTok{ }\NormalTok{proportion))) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{color =} \StringTok{"gray40"}\NormalTok{, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{width =} \FloatTok{0.3}\NormalTok{, }\DataTypeTok{height =} \FloatTok{0.3}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ palavra), }\DataTypeTok{check_overlap =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{vjust =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_x_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_y_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_color_gradient}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.001}\NormalTok{),}
                         \DataTypeTok{low =} \StringTok{"darkslategray4"}\NormalTok{, }\DataTypeTok{high =} \StringTok{"gray75"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{y =} \StringTok{"DEA"}\NormalTok{, }\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 3087 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 3086 rows containing missing values (geom_text).
\end{verbatim}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-63-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Warning messages:}
\FunctionTok{1:}\AttributeTok{ Removed 3812 rows containing missing values (geom_point). }
\FunctionTok{2:}\AttributeTok{ Removed 3813 rows containing missing values (geom_text).}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ freq05[freq05}\OperatorTok{$}\NormalTok{DIRETORIA }\OperatorTok{==}\StringTok{ "DGC"}\NormalTok{,],}
             \OperatorTok{~}\StringTok{ }\NormalTok{proportion }\OperatorTok{+}\StringTok{ `}\DataTypeTok{DEA}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  proportion and DEA
## t = 7.5906, df = 627, p-value = 1.158e-13
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.2168448 0.3601121
## sample estimates:
##      cor 
## 0.290103
\end{verbatim}

\begin{itemize}
\tightlist
\item
  DEA X OUTROS
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq06 <-}\StringTok{ }\NormalTok{PROP_PALAVRA }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{gather}\NormalTok{(DIRETORIA, proportion, }\KeywordTok{c}\NormalTok{(}\StringTok{`}\DataTypeTok{OUTROS}\StringTok{`}\NormalTok{))}
  
  \KeywordTok{library}\NormalTok{(scales)}
  \CommentTok{# expect a warning about rows with missing values being removed}
  \KeywordTok{ggplot}\NormalTok{(freq06, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ proportion, }\DataTypeTok{y =} \StringTok{`}\DataTypeTok{DEA}\StringTok{`}\NormalTok{,}
                        \DataTypeTok{color =} \KeywordTok{abs}\NormalTok{(}\StringTok{`}\DataTypeTok{DEA}\StringTok{`} \OperatorTok{-}\StringTok{ }\NormalTok{proportion))) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{color =} \StringTok{"gray40"}\NormalTok{, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{width =} \FloatTok{0.3}\NormalTok{, }\DataTypeTok{height =} \FloatTok{0.3}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ palavra), }\DataTypeTok{check_overlap =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{vjust =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_x_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_y_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_color_gradient}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.001}\NormalTok{),}
                         \DataTypeTok{low =} \StringTok{"darkslategray4"}\NormalTok{, }\DataTypeTok{high =} \StringTok{"gray75"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{y =} \StringTok{"DEA"}\NormalTok{, }\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 3500 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 3498 rows containing missing values (geom_text).
\end{verbatim}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-65-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Warning messages:}
\FunctionTok{1:}\AttributeTok{ Removed 4303 rows containing missing values (geom_point). }
\FunctionTok{2:}\AttributeTok{ Removed 4304 rows containing missing values (geom_text). }
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ freq06[freq06}\OperatorTok{$}\NormalTok{DIRETORIA }\OperatorTok{==}\StringTok{ "OUTROS"}\NormalTok{,],}
             \OperatorTok{~}\StringTok{ }\NormalTok{proportion }\OperatorTok{+}\StringTok{ `}\DataTypeTok{DEA}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  proportion and DEA
## t = 10.187, df = 215, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4733414 0.6540412
## sample estimates:
##       cor 
## 0.5705569
\end{verbatim}

\begin{itemize}
\tightlist
\item
  DPG X DGC
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq07 <-}\StringTok{ }\NormalTok{PROP_PALAVRA }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{gather}\NormalTok{(DIRETORIA, proportion, }\KeywordTok{c}\NormalTok{(}\StringTok{`}\DataTypeTok{DGC}\StringTok{`}\NormalTok{))}
  
  \KeywordTok{library}\NormalTok{(scales)}
  \CommentTok{# expect a warning about rows with missing values being removed}
  \KeywordTok{ggplot}\NormalTok{(freq07, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ proportion, }\DataTypeTok{y =} \StringTok{`}\DataTypeTok{DPG}\StringTok{`}\NormalTok{,}
                        \DataTypeTok{color =} \KeywordTok{abs}\NormalTok{(}\StringTok{`}\DataTypeTok{DPG}\StringTok{`} \OperatorTok{-}\StringTok{ }\NormalTok{proportion))) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{color =} \StringTok{"gray40"}\NormalTok{, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{width =} \FloatTok{0.3}\NormalTok{, }\DataTypeTok{height =} \FloatTok{0.3}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ palavra), }\DataTypeTok{check_overlap =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{vjust =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_x_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_y_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_color_gradient}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.001}\NormalTok{),}
                         \DataTypeTok{low =} \StringTok{"darkslategray4"}\NormalTok{, }\DataTypeTok{high =} \StringTok{"gray75"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{y =} \StringTok{"DPG"}\NormalTok{, }\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 3507 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 3507 rows containing missing values (geom_text).
\end{verbatim}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-67-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Warning messages:}
\FunctionTok{1:}\AttributeTok{ Removed 4296 rows containing missing values (geom_point). }
\FunctionTok{2:}\AttributeTok{ Removed 4297 rows containing missing values (geom_text). }
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ freq07[freq07}\OperatorTok{$}\NormalTok{DIRETORIA }\OperatorTok{==}\StringTok{ "DGC"}\NormalTok{,],}
             \OperatorTok{~}\StringTok{ }\NormalTok{proportion }\OperatorTok{+}\StringTok{ `}\DataTypeTok{DPG}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  proportion and DPG
## t = 3.4202, df = 206, p-value = 0.0007543
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.09888554 0.35660374
## sample estimates:
##       cor 
## 0.2318083
\end{verbatim}

\begin{itemize}
\tightlist
\item
  DPG X OUTROS
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq08 <-}\StringTok{ }\NormalTok{PROP_PALAVRA }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{gather}\NormalTok{(DIRETORIA, proportion, }\KeywordTok{c}\NormalTok{(}\StringTok{`}\DataTypeTok{OUTROS}\StringTok{`}\NormalTok{))}
  
  \KeywordTok{library}\NormalTok{(scales)}
  \CommentTok{# expect a warning about rows with missing values being removed}
  \KeywordTok{ggplot}\NormalTok{(freq08, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ proportion, }\DataTypeTok{y =} \StringTok{`}\DataTypeTok{DPG}\StringTok{`}\NormalTok{,}
                        \DataTypeTok{color =} \KeywordTok{abs}\NormalTok{(}\StringTok{`}\DataTypeTok{DPG}\StringTok{`} \OperatorTok{-}\StringTok{ }\NormalTok{proportion))) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{color =} \StringTok{"gray40"}\NormalTok{, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{width =} \FloatTok{0.3}\NormalTok{, }\DataTypeTok{height =} \FloatTok{0.3}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ palavra), }\DataTypeTok{check_overlap =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{vjust =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_x_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_y_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_color_gradient}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.001}\NormalTok{),}
                         \DataTypeTok{low =} \StringTok{"darkslategray4"}\NormalTok{, }\DataTypeTok{high =} \StringTok{"gray75"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{y =} \StringTok{"DPG"}\NormalTok{, }\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 3623 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 3623 rows containing missing values (geom_text).
\end{verbatim}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-69-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Warning messages:}
\FunctionTok{1:}\AttributeTok{ Removed 4450 rows containing missing values (geom_point). }
\FunctionTok{2:}\AttributeTok{ Removed 4451 rows containing missing values (geom_text). }
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ freq08[freq08}\OperatorTok{$}\NormalTok{DIRETORIA }\OperatorTok{==}\StringTok{ "OUTROS"}\NormalTok{,],}
             \OperatorTok{~}\StringTok{ }\NormalTok{proportion }\OperatorTok{+}\StringTok{ `}\DataTypeTok{DPG}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  proportion and DPG
## t = 5.0342, df = 90, p-value = 2.447e-06
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.2919524 0.6145567
## sample estimates:
##       cor 
## 0.4687405
\end{verbatim}

\begin{itemize}
\tightlist
\item
  DGC X OUTROS
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freq09 <-}\StringTok{ }\NormalTok{PROP_PALAVRA }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{gather}\NormalTok{(DIRETORIA, proportion, }\KeywordTok{c}\NormalTok{(}\StringTok{`}\DataTypeTok{OUTROS}\StringTok{`}\NormalTok{))}
  
  \KeywordTok{library}\NormalTok{(scales)}
  \CommentTok{# expect a warning about rows with missing values being removed}
  \KeywordTok{ggplot}\NormalTok{(freq08, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ proportion, }\DataTypeTok{y =} \StringTok{`}\DataTypeTok{DGC}\StringTok{`}\NormalTok{,}
                        \DataTypeTok{color =} \KeywordTok{abs}\NormalTok{(}\StringTok{`}\DataTypeTok{DGC}\StringTok{`} \OperatorTok{-}\StringTok{ }\NormalTok{proportion))) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{color =} \StringTok{"gray40"}\NormalTok{, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{width =} \FloatTok{0.3}\NormalTok{, }\DataTypeTok{height =} \FloatTok{0.3}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ palavra), }\DataTypeTok{check_overlap =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{vjust =} \FloatTok{1.5}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_x_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_y_log10}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{percent_format}\NormalTok{(}\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{, }\DataTypeTok{decimal.mark =} \StringTok{","}\NormalTok{, }\DataTypeTok{accuracy =} \DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\OtherTok{NA}\NormalTok{, }\FloatTok{0.01}\NormalTok{)) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_color_gradient}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.001}\NormalTok{),}
                         \DataTypeTok{low =} \StringTok{"darkslategray4"}\NormalTok{, }\DataTypeTok{high =} \StringTok{"gray75"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{y =} \StringTok{"DGC"}\NormalTok{, }\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 3510 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 3510 rows containing missing values (geom_text).
\end{verbatim}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-71-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{Warning messages:}
\FunctionTok{1:}\AttributeTok{ Removed 4302 rows containing missing values (geom_point). }
\FunctionTok{2:}\AttributeTok{ Removed 4303 rows containing missing values (geom_text).}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ freq09[freq09}\OperatorTok{$}\NormalTok{DIRETORIA }\OperatorTok{==}\StringTok{ "OUTROS"}\NormalTok{,],}
             \OperatorTok{~}\StringTok{ }\NormalTok{proportion }\OperatorTok{+}\StringTok{ `}\DataTypeTok{DGC}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  proportion and DGC
## t = 8.4142, df = 203, p-value = 7.03e-15
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.3992974 0.6034898
## sample estimates:
##      cor 
## 0.508508
\end{verbatim}

\subsubsection{Usando bigram para n=2 palavras por
token}\label{usando-bigram-para-n2-palavras-por-token}

\paragraph{Frequência de palavras por
diretoria}\label{frequencia-de-palavras-por-diretoria-4}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diretoria_palavras_bigram <-}\StringTok{ }\NormalTok{DB }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(DESCRI_PEDIDO,DIRETORIA) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unnest_tokens}\NormalTok{(BIGRAM, DESCRI_PEDIDO, }\DataTypeTok{token =} \StringTok{"ngrams"}\NormalTok{, }\DataTypeTok{n =} \DecValTok{2}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(DIRETORIA, BIGRAM, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}
\CommentTok{#diretoria_palavras_bigram}

\NormalTok{plot_diretoria_palavras_bigram <-}\StringTok{ }\NormalTok{diretoria_palavras_bigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{bind_tf_idf}\NormalTok{(BIGRAM, DIRETORIA, n) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(tf_idf)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{BIGRAM =} \KeywordTok{factor}\NormalTok{(BIGRAM, }\DataTypeTok{levels =} \KeywordTok{rev}\NormalTok{(}\KeywordTok{unique}\NormalTok{(BIGRAM)))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DIRETORIA =} \KeywordTok{factor}\NormalTok{(DIRETORIA, }\DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\StringTok{"DEA"}\NormalTok{,}
                                                  \StringTok{"DEE"}\NormalTok{,}
                                                  \StringTok{"DGC"}\NormalTok{,}
                                                  \StringTok{"DPG"}\NormalTok{,}
                                                  \StringTok{"OUTROS"}\NormalTok{)))}
\CommentTok{#View(head(plot_diretoria_palavras_bigram))}
\CommentTok{#jpeg("02_freq_palavras_dir.jpeg")}
\NormalTok{plot_diretoria_palavras_bigram }\OperatorTok{%>%}
\KeywordTok{group_by}\NormalTok{(DIRETORIA) }\OperatorTok{%>%}
\KeywordTok{top_n}\NormalTok{(}\DecValTok{10}\NormalTok{, tf_idf) }\OperatorTok{%>%}
\KeywordTok{ungroup}\NormalTok{() }\OperatorTok{%>%}
\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{BIGRAM =} \KeywordTok{reorder}\NormalTok{(BIGRAM, tf_idf)) }\OperatorTok{%>%}
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(BIGRAM, tf_idf, }\DataTypeTok{fill =}\NormalTok{ DIRETORIA)) }\OperatorTok{+}
\KeywordTok{geom_col}\NormalTok{(}\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{, }\DataTypeTok{y =} \StringTok{"tf-idf"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{, }\DataTypeTok{scales =} \StringTok{"free"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{gcomma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/03_freq_palavras_dir-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#dev.off()}
\end{Highlighting}
\end{Shaded}

\subsubsection{Usando bigram para n=3 palavras por
token}\label{usando-bigram-para-n3-palavras-por-token}

\paragraph{Frequência de palavras por
diretoria}\label{frequencia-de-palavras-por-diretoria-5}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diretoria_palavras_trigram <-}\StringTok{ }\NormalTok{DB }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(DESCRI_PEDIDO,DIRETORIA) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unnest_tokens}\NormalTok{(TRIGRAM, DESCRI_PEDIDO, }\DataTypeTok{token =} \StringTok{"ngrams"}\NormalTok{, }\DataTypeTok{n =} \DecValTok{3}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(DIRETORIA, TRIGRAM, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ungroup}\NormalTok{()}
\CommentTok{#diretoria_palavras_trigram}

\NormalTok{plot_diretoria_palavras_trigram <-}\StringTok{ }\NormalTok{diretoria_palavras_trigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{bind_tf_idf}\NormalTok{(TRIGRAM, DIRETORIA, n) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(tf_idf)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{TRIGRAM =} \KeywordTok{factor}\NormalTok{(TRIGRAM, }\DataTypeTok{levels =} \KeywordTok{rev}\NormalTok{(}\KeywordTok{unique}\NormalTok{(TRIGRAM)))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DIRETORIA =} \KeywordTok{factor}\NormalTok{(DIRETORIA, }\DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\StringTok{"DEA"}\NormalTok{,}
                                                  \StringTok{"DEE"}\NormalTok{,}
                                                  \StringTok{"DGC"}\NormalTok{,}
                                                  \StringTok{"DPG"}\NormalTok{,}
                                                  \StringTok{"OUTROS"}\NormalTok{)))}
\CommentTok{#View(head(plot_diretoria_palavras_trigram))}
\CommentTok{#jpeg("02_freq_palavras_dir.jpeg")}
\NormalTok{plot_diretoria_palavras_trigram }\OperatorTok{%>%}
\KeywordTok{group_by}\NormalTok{(DIRETORIA) }\OperatorTok{%>%}
\KeywordTok{top_n}\NormalTok{(}\DecValTok{10}\NormalTok{, tf_idf) }\OperatorTok{%>%}
\KeywordTok{ungroup}\NormalTok{() }\OperatorTok{%>%}
\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{TRIGRAM =} \KeywordTok{reorder}\NormalTok{(TRIGRAM, tf_idf)) }\OperatorTok{%>%}
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(TRIGRAM, tf_idf, }\DataTypeTok{fill =}\NormalTok{ DIRETORIA)) }\OperatorTok{+}
\KeywordTok{geom_col}\NormalTok{(}\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{, }\DataTypeTok{y =} \StringTok{"tf-idf"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{, }\DataTypeTok{scales =} \StringTok{"free"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{gcomma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/04_freq_palavras_dir-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#dev.off()}
\end{Highlighting}
\end{Shaded}

\subsection{tidy object into document-term
matrix}\label{tidy-object-into-document-term-matrix}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot_diretoria_palavras <-}\StringTok{ }\NormalTok{diretoria_palavras }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{bind_tf_idf}\NormalTok{(palavra, DIRETORIA, n) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(tf_idf)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{palavra =} \KeywordTok{factor}\NormalTok{(palavra, }\DataTypeTok{levels =} \KeywordTok{rev}\NormalTok{(}\KeywordTok{unique}\NormalTok{(palavra)))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DIRETORIA =} \KeywordTok{factor}\NormalTok{(DIRETORIA, }\DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\StringTok{"DEA"}\NormalTok{,}
                                                  \StringTok{"DEE"}\NormalTok{,}
                                                  \StringTok{"DGC"}\NormalTok{,}
                                                  \StringTok{"DPG"}\NormalTok{,}
                                                  \StringTok{"OUTROS"}\NormalTok{)))}

\NormalTok{dtm =}\StringTok{ }\NormalTok{plot_diretoria_palavras }\OperatorTok{%>%}
\KeywordTok{cast_dtm}\NormalTok{(}\DataTypeTok{document =}\NormalTok{ DIRETORIA, }\DataTypeTok{term =}\NormalTok{ palavra, n)}
\end{Highlighting}
\end{Shaded}

\subsubsection{Nuvem de palavras}\label{nuvem-de-palavras}

\paragraph{Nuvem de palavras por diretoria - s/ steeming e/ c/ stopwords
-
onegram}\label{nuvem-de-palavras-por-diretoria---s-steeming-e-c-stopwords---onegram}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#View(head(plot_diretoria_palavras))}
\KeywordTok{library}\NormalTok{(wordcloud)}
\NormalTok{plot_diretorias_tf_dif =}\StringTok{ }\NormalTok{plot_diretoria_palavras }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{select}\NormalTok{(palavra, tf_idf, DIRETORIA) }\OperatorTok{%>%}
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{palavra =} \KeywordTok{reorder}\NormalTok{(palavra, tf_idf))}

\NormalTok{## DEE}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DEE.jpeg")}
\NormalTok{nuvem1 =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DEE"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ palavra,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{231321}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem1}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem1}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.2}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-46-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DGC}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir02_DGC.jpeg")}
\NormalTok{nuvem2 =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DGC"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ palavra,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{75437}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem2}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem2}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.2}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-46-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DEA}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir03_DEA.jpeg")}
\NormalTok{nuvem3 =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DEA"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ palavra,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{231321}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem3}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem3}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.2}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-46-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DPG}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir04_DPG.jpeg")}
\NormalTok{nuvem4 =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DPG"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ palavra,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{75437}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem4}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem4}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.1}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-46-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## OUTROS}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir05_OUTROS.jpeg")}
\NormalTok{nuvem5 =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "OUTROS"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ palavra,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{75437}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem5}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem5}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.1}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-46-5.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#View(head(plot_diretoria_palavras))}
\NormalTok{library(wordcloud2)}

\NormalTok{plot_diretorias_tf_dif = plot_diretoria_palavras %>%}
\NormalTok{    select(palavra, tf_idf, DIRETORIA) %>%}
\NormalTok{    mutate(palavra = reorder(palavra, tf_idf))}

\CommentTok{## DEE}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DEE.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DEE"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2(shuffle = TRUE, }
\NormalTok{             color = }\StringTok{"random-dark"}\NormalTok{,}
\NormalTok{             shape = }\StringTok{"circle"}\NormalTok{)}

\CommentTok{## DGC}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DGC.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DGC"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}

\CommentTok{## DEA}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DEA.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DEA"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}

\CommentTok{## DPG}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir04_DPG.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DPG"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}
  
\CommentTok{## OUTROS}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_OUTROS.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"OUTROS"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}
\end{Highlighting}
\end{Shaded}

--\textgreater{}

\paragraph{Nuvem de palavras por diretoria - s/ steeming e/ou remoção de
stopwords -
bigram}\label{nuvem-de-palavras-por-diretoria---s-steeming-eou-remocao-de-stopwords---bigram}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot_diretorias_tf_dif_bigram =}\StringTok{ }\NormalTok{DB }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(DESCRI_PEDIDO,DIRETORIA) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unnest_tokens}\NormalTok{(BIGRAM, DESCRI_PEDIDO, }\DataTypeTok{token =} \StringTok{"ngrams"}\NormalTok{, }\DataTypeTok{n =} \DecValTok{2}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(DIRETORIA, BIGRAM, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{bind_tf_idf}\NormalTok{(BIGRAM, DIRETORIA, n) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(tf_idf)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{BIGRAM =} \KeywordTok{factor}\NormalTok{(BIGRAM, }\DataTypeTok{levels =} \KeywordTok{rev}\NormalTok{(}\KeywordTok{unique}\NormalTok{(BIGRAM)))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DIRETORIA =} \KeywordTok{factor}\NormalTok{(DIRETORIA,}\DataTypeTok{levels=}\KeywordTok{c}\NormalTok{(}\StringTok{"DEA"}\NormalTok{,}\StringTok{"DEE"}\NormalTok{,}\StringTok{"DGC"}\NormalTok{,}\StringTok{"DPG"}\NormalTok{,}\StringTok{"OUTROS"}\NormalTok{))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(BIGRAM, tf_idf, DIRETORIA)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DEE}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DEE.jpeg")}
\NormalTok{nuvem1.}\DecValTok{2}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_bigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DEE"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ BIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{231321}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem1.}\DecValTok{2}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem1.}\DecValTok{2}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.2}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_onegram_DIR01_semstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DGC}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir02_DGC.jpeg")}
\NormalTok{nuvem2.}\DecValTok{2}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_bigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DGC"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ BIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{75437}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem2.}\DecValTok{2}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem2.}\DecValTok{2}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.2}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_onegram_DIR02_semstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DEA}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir03_DEA.jpeg")}
\NormalTok{nuvem3.}\DecValTok{2}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_bigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DEA"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ BIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{543453}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem3.}\DecValTok{2}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem3.}\DecValTok{2}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.2}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_onegram_DIR03_semstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DPG}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir04_DPG.jpeg")}
\NormalTok{nuvem4.}\DecValTok{2}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_bigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DPG"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ BIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{75437}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem4.}\DecValTok{2}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem4.}\DecValTok{2}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.1}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_onegram_DIR04_semstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## OUTROS}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir05_OUTROS.jpeg")}
\NormalTok{nuvem5.}\DecValTok{2}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_bigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "OUTROS"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ BIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{75437}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem5.}\DecValTok{2}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem5.}\DecValTok{2}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.1}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_onegram_DIR05_semstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#View(head(plot_diretoria_palavras))}
\NormalTok{library(wordcloud2)}

\NormalTok{plot_diretorias_tf_dif_bigram = DB %>%}
\NormalTok{  select(DESCRI_PEDIDO,DIRETORIA) %>%}
\NormalTok{  unnest_tokens(BIGRAM, DESCRI_PEDIDO, token = }\StringTok{"ngrams"}\NormalTok{, n = 2) %>%}
\NormalTok{  count(DIRETORIA, BIGRAM, sort = TRUE) %>%}
\NormalTok{  bind_tf_idf(BIGRAM, DIRETORIA, n) %>%}
\NormalTok{  arrange(desc(tf_idf)) %>%}
\NormalTok{  mutate(BIGRAM = factor(BIGRAM, levels = rev(unique(BIGRAM)))) %>%}
\NormalTok{  mutate(DIRETORIA = factor(DIRETORIA,levels=c(}\StringTok{"DEA"}\NormalTok{,}\StringTok{"DEE"}\NormalTok{,}\StringTok{"DGC"}\NormalTok{,}\StringTok{"DPG"}\NormalTok{,}\StringTok{"OUTROS"}\NormalTok{))) %>%}
\NormalTok{  select(BIGRAM, tf_idf, DIRETORIA)}
  

\CommentTok{## DEE}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DEE.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_bigram %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DEE"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2(shuffle = TRUE, }
\NormalTok{             color = }\StringTok{"random-dark"}\NormalTok{,}
\NormalTok{             shape = }\StringTok{"circle"}\NormalTok{)}

\CommentTok{## DGC}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DGC.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_bigram %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DGC"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}

\CommentTok{## DEA}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DEA.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_bigram %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DEA"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}

\CommentTok{## DPG}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DPG.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_bigram %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DPG"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}
\end{Highlighting}
\end{Shaded}

\subparagraph{\texorpdfstring{Separando palavras de um bigram em
``palavra1'' e ``palavra2'' p/ remover
stopwords}{Separando palavras de um bigram em palavra1 e palavra2 p/ remover stopwords}}\label{separando-palavras-de-um-bigram-em-palavra1-e-palavra2-p-remover-stopwords}

Considerando já a exclusão de casos onde houver stopwords consecultivos
na ``palavra1'' e ``palavra2'', ou seja onde
\(palavra1=stopword \land palavra2=stopword\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bigrams =}\StringTok{ }\NormalTok{DB }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(DESCRI_PEDIDO,DIRETORIA) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unnest_tokens}\NormalTok{(BIGRAM, DESCRI_PEDIDO, }\DataTypeTok{token =} \StringTok{"ngrams"}\NormalTok{, }\DataTypeTok{n =} \DecValTok{2}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(DIRETORIA, BIGRAM, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{) }

\NormalTok{separa_bigrams =}\StringTok{ }\NormalTok{bigrams }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{separate}\NormalTok{(BIGRAM, }\KeywordTok{c}\NormalTok{(}\StringTok{"palavra1"}\NormalTok{, }\StringTok{"palavra2"}\NormalTok{), }\DataTypeTok{sep =} \StringTok{" "}\NormalTok{)}

\NormalTok{junta_bigrams =}\StringTok{ }\NormalTok{separa_bigrams }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unite}\NormalTok{(BIGRAM, palavra1, palavra2, }\DataTypeTok{sep =} \StringTok{" "}\NormalTok{)}
\CommentTok{# levels(as.factor(junta_bigrams$BIGRAM == bigrams$BIGRAM))   # CHECK}

\NormalTok{## remove stopwords  }
\NormalTok{bigrams2 =}\StringTok{ }\KeywordTok{cbind}\NormalTok{(separa_bigrams,}\DataTypeTok{BIGRAM =}\NormalTok{ junta_bigrams}\OperatorTok{$}\NormalTok{BIGRAM) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{palavra1 }\OperatorTok{%in%}\StringTok{ }\NormalTok{mystopwords}\OperatorTok{$}\NormalTok{palavra) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{palavra2 }\OperatorTok{%in%}\StringTok{ }\NormalTok{mystopwords}\OperatorTok{$}\NormalTok{palavra) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{palavra1 }\OperatorTok{%in%}\StringTok{ "a"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{palavra2 }\OperatorTok{%in%}\StringTok{ "a"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{palavra1 }\OperatorTok{%in%}\StringTok{ "p"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{palavra1 }\OperatorTok{%in%}\StringTok{ "s"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{palavra1 }\OperatorTok{%in%}\StringTok{ "d"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{palavra2 }\OperatorTok{%in%}\StringTok{ "p"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{palavra2 }\OperatorTok{%in%}\StringTok{ "s"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{palavra2 }\OperatorTok{%in%}\StringTok{ "d"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\NormalTok{palavra2 }\OperatorTok{%in%}\StringTok{ "s.a"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra1, }\StringTok{"0"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra1, }\StringTok{"1"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra1, }\StringTok{"2"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra1, }\StringTok{"3"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra1, }\StringTok{"4"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra1, }\StringTok{"5"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra1, }\StringTok{"6"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra1, }\StringTok{"7"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra1, }\StringTok{"8"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra1, }\StringTok{"9"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra2, }\StringTok{"0"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra2, }\StringTok{"1"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra2, }\StringTok{"2"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra2, }\StringTok{"3"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra2, }\StringTok{"4"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra2, }\StringTok{"5"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra2, }\StringTok{"6"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra2, }\StringTok{"7"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra2, }\StringTok{"8"}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{str_detect}\NormalTok{(palavra2, }\StringTok{"9"}\NormalTok{))}
  \CommentTok{#count(DIRETORIA, BIGRAM) }
\end{Highlighting}
\end{Shaded}

\paragraph{Nuvem de palavras por diretoria - s/ steeming c/ remoção de
stopwords -
bigram}\label{nuvem-de-palavras-por-diretoria---s-steeming-c-remocao-de-stopwords---bigram}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#View(head(plot_diretoria_palavras))}
\KeywordTok{library}\NormalTok{(wordcloud2)}
\KeywordTok{library}\NormalTok{(wordcloud)}
\NormalTok{plot_diretorias_tf_dif_bigram2 =}\StringTok{ }\NormalTok{bigrams2 }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(BIGRAM,n,DIRETORIA) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{bind_tf_idf}\NormalTok{(BIGRAM, DIRETORIA, n) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(tf_idf)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{BIGRAM =} \KeywordTok{factor}\NormalTok{(BIGRAM, }\DataTypeTok{levels =} \KeywordTok{rev}\NormalTok{(}\KeywordTok{unique}\NormalTok{(BIGRAM)))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DIRETORIA =} \KeywordTok{factor}\NormalTok{(DIRETORIA,}\DataTypeTok{levels=}\KeywordTok{c}\NormalTok{(}\StringTok{"DEA"}\NormalTok{,}\StringTok{"DEE"}\NormalTok{,}\StringTok{"DGC"}\NormalTok{,}\StringTok{"DPG"}\NormalTok{,}\StringTok{"OUTROS"}\NormalTok{))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(BIGRAM, tf_idf, DIRETORIA)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DEE}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DEE.jpeg")}
\NormalTok{nuvem1.}\DecValTok{2}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_bigram2 }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DEE"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ BIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{231321}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem1.}\DecValTok{2}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem1.}\DecValTok{2}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.2}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_bigram_DIR01_semstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DGC}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir02_DGC.jpeg")}
\NormalTok{nuvem2.}\DecValTok{2}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_bigram2 }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DGC"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ BIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{95654}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem2.}\DecValTok{2}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem2.}\DecValTok{2}\OperatorTok{$}\NormalTok{freq,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_bigram_DIR02_semstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DEA}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir03_DEA.jpeg")}
\NormalTok{nuvem3.}\DecValTok{2}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_bigram2 }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DEA"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ BIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{543453}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem3.}\DecValTok{2}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem3.}\DecValTok{2}\OperatorTok{$}\NormalTok{freq,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_bigram_DIR03_semstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DPG}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir04_DPG.jpeg")}
\NormalTok{nuvem4.}\DecValTok{2}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_bigram2 }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DPG"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ BIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{75437}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem4.}\DecValTok{2}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem4.}\DecValTok{2}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.1}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_bigram_DIR04_semstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## OUTROS}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir05_OUTROS.jpeg")}
\NormalTok{nuvem5.}\DecValTok{2}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_bigram2 }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "OUTROS"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ BIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{75437}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem5.}\DecValTok{2}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem5.}\DecValTok{2}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.1}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_bigram_DIR05_semstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#View(head(plot_diretoria_palavras))}
\NormalTok{library(wordcloud2)}

\NormalTok{plot_diretorias_tf_dif_bigram2 = bigrams2 %>%}
\NormalTok{  select(BIGRAM,n,DIRETORIA) %>%}
\NormalTok{  bind_tf_idf(BIGRAM, DIRETORIA, n) %>%}
\NormalTok{  arrange(desc(tf_idf)) %>%}
\NormalTok{  mutate(BIGRAM = factor(BIGRAM, levels = rev(unique(BIGRAM)))) %>%}
\NormalTok{  mutate(DIRETORIA = factor(DIRETORIA,levels=c(}\StringTok{"DEA"}\NormalTok{,}\StringTok{"DEE"}\NormalTok{,}\StringTok{"DGC"}\NormalTok{,}\StringTok{"DPG"}\NormalTok{,}\StringTok{"OUTROS"}\NormalTok{))) %>%}
\NormalTok{  select(BIGRAM, tf_idf, DIRETORIA)}
  

\CommentTok{## DEE}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DEE.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_bigram2 %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DEE"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2(shuffle = TRUE, }
\NormalTok{             color = }\StringTok{"random-dark"}\NormalTok{,}
\NormalTok{             shape = }\StringTok{"circle"}\NormalTok{)}

\CommentTok{## DGC}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir02_DGC.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_bigram2 %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DGC"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}

\CommentTok{## DEA}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir03_DEA.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_bigram2 %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DEA"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}

\CommentTok{## DPG}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir04_DPG.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_bigram2 %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DPG"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}

\CommentTok{## OUTROS}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir05_OUTROS.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_bigram2 %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"OUTROS"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}
\end{Highlighting}
\end{Shaded}

\paragraph{Gráfico da estatística tf\_idf c/ remoção de
stopwords}\label{grafico-da-estatistica-tf_idf-c-remocao-de-stopwords}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot_diretorias_tf_dif_bigram2 }\OperatorTok{%>%}
\KeywordTok{group_by}\NormalTok{(DIRETORIA) }\OperatorTok{%>%}
\KeywordTok{top_n}\NormalTok{(}\DecValTok{10}\NormalTok{, tf_idf) }\OperatorTok{%>%}
\KeywordTok{ungroup}\NormalTok{() }\OperatorTok{%>%}
\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{BIGRAM =} \KeywordTok{reorder}\NormalTok{(BIGRAM, tf_idf)) }\OperatorTok{%>%}
\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(BIGRAM, tf_idf, }\DataTypeTok{fill =}\NormalTok{ DIRETORIA)) }\OperatorTok{+}
\KeywordTok{geom_col}\NormalTok{(}\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \OtherTok{NULL}\NormalTok{, }\DataTypeTok{y =} \StringTok{"tf-idf"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{DIRETORIA, }\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{, }\DataTypeTok{scales =} \StringTok{"free"}\NormalTok{) }\OperatorTok{+}
\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels=}\NormalTok{gcomma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-50-1.pdf}

\paragraph{Nuvem de palavras por diretoria - s/ steeming e/ou stopwords
-
trigram}\label{nuvem-de-palavras-por-diretoria---s-steeming-eou-stopwords---trigram}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#View(head(plot_diretoria_palavras))}
\KeywordTok{library}\NormalTok{(wordcloud)}
\NormalTok{plot_diretorias_tf_dif_trigram =}\StringTok{ }\NormalTok{DB }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(DESCRI_PEDIDO,DIRETORIA) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{unnest_tokens}\NormalTok{(TRIGRAM, DESCRI_PEDIDO, }\DataTypeTok{token =} \StringTok{"ngrams"}\NormalTok{, }\DataTypeTok{n =} \DecValTok{3}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(DIRETORIA, TRIGRAM, }\DataTypeTok{sort =} \OtherTok{TRUE}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{bind_tf_idf}\NormalTok{(TRIGRAM, DIRETORIA, n) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(tf_idf)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{TRIGRAM =} \KeywordTok{factor}\NormalTok{(TRIGRAM, }\DataTypeTok{levels =} \KeywordTok{rev}\NormalTok{(}\KeywordTok{unique}\NormalTok{(TRIGRAM)))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{DIRETORIA =} \KeywordTok{factor}\NormalTok{(DIRETORIA,}\DataTypeTok{levels=}\KeywordTok{c}\NormalTok{(}\StringTok{"DEA"}\NormalTok{,}\StringTok{"DEE"}\NormalTok{,}\StringTok{"DGC"}\NormalTok{,}\StringTok{"DPG"}\NormalTok{,}\StringTok{"OUTROS"}\NormalTok{))) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(TRIGRAM, tf_idf, DIRETORIA)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DEE}
\CommentTok{#jpeg("wordcloud_tfidf_dir01_DEE_trigram_comstop_semstemming.jpeg")}
\NormalTok{nuvem1.}\DecValTok{3}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_trigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DEE"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ TRIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{8835}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem1.}\DecValTok{3}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem1.}\DecValTok{3}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.2}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_trigram_DIR01_comstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#dev.off()}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DGC}
\CommentTok{#jpeg("wordcloud_tfidf_dir02_DGC_trigram_comstop_semstemming.jpeg")}
\NormalTok{nuvem2.}\DecValTok{3}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_trigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DGC"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ TRIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1273}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem2.}\DecValTok{3}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem2.}\DecValTok{3}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.2}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_trigram_DIR02_comstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DEA}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir03_DEA_trigram_comstop_semstemming.jpeg")}
\NormalTok{nuvem3.}\DecValTok{3}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_trigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DEA"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ TRIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{543453}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem3.}\DecValTok{3}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem3.}\DecValTok{3}\OperatorTok{$}\NormalTok{freq,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_trigram_DIR03_comstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## DPG}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir04_DPG_trigram_comstop_semstemming.jpeg")}
\NormalTok{nuvem4.}\DecValTok{3}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_trigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "DPG"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ TRIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{75437}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem4.}\DecValTok{3}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem4.}\DecValTok{3}\OperatorTok{$}\NormalTok{freq, }\DataTypeTok{min.freq =} \FloatTok{0.1}\NormalTok{,}
          \DataTypeTok{max.words=}\DecValTok{250}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_trigram_DIR04_comstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{## OUTROS}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir05_OUTROS_trigram_comstop_semstemming.jpeg")}
\NormalTok{nuvem5.}\DecValTok{3}\NormalTok{ =}\StringTok{ }
\NormalTok{plot_diretorias_tf_dif_trigram }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(DIRETORIA }\OperatorTok{==}\StringTok{ "OUTROS"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(}\OperatorTok{-}\NormalTok{DIRETORIA, }\DataTypeTok{word =}\NormalTok{ TRIGRAM,}\DataTypeTok{freq =}\NormalTok{ tf_idf) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{#top_n(150, freq) %>%}
\StringTok{  }\KeywordTok{as.data.frame}\NormalTok{() }

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1235}\NormalTok{)}
\KeywordTok{wordcloud}\NormalTok{(}\DataTypeTok{words =}\NormalTok{ nuvem5.}\DecValTok{3}\OperatorTok{$}\NormalTok{word, }\DataTypeTok{freq =}\NormalTok{ nuvem5.}\DecValTok{3}\OperatorTok{$}\NormalTok{freq,}
          \DataTypeTok{max.words=}\DecValTok{100}\NormalTok{, }\DataTypeTok{random.order=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{rot.per=}\FloatTok{0.35}\NormalTok{, }
          \DataTypeTok{colors=}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{10}\NormalTok{, }\StringTok{"Dark2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/wordcloud_trigram_DIR05_comstopwords-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#View(head(plot_diretoria_palavras))}
\NormalTok{library(wordcloud2)}

\NormalTok{plot_diretorias_tf_dif_trigram = DB %>%}
\NormalTok{  select(DESCRI_PEDIDO,DIRETORIA) %>%}
\NormalTok{  unnest_tokens(TRIGRAM, DESCRI_PEDIDO, token = }\StringTok{"ngrams"}\NormalTok{, n = 3) %>%}
\NormalTok{  count(DIRETORIA, TRIGRAM, sort = TRUE) %>%}
\NormalTok{  bind_tf_idf(TRIGRAM, DIRETORIA, n) %>%}
\NormalTok{  arrange(desc(tf_idf)) %>%}
\NormalTok{  mutate(TRIGRAM = factor(TRIGRAM, levels = rev(unique(TRIGRAM)))) %>%}
\NormalTok{  mutate(DIRETORIA = factor(DIRETORIA,levels=c(}\StringTok{"DEA"}\NormalTok{,}\StringTok{"DEE"}\NormalTok{,}\StringTok{"DGC"}\NormalTok{,}\StringTok{"DPG"}\NormalTok{,}\StringTok{"OUTROS"}\NormalTok{))) %>%}
\NormalTok{  select(TRIGRAM, tf_idf, DIRETORIA)}
  

\CommentTok{## DEE}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir01_DEE.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_trigram %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DEE"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2(shuffle = TRUE, }
\NormalTok{             color = }\StringTok{"random-dark"}\NormalTok{,}
\NormalTok{             shape = }\StringTok{"circle"}\NormalTok{)}

\CommentTok{## DGC}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir02_DGC.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_trigram %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DGC"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}

\CommentTok{## DEA}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir03_DEA.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_trigram %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DEA"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}

\CommentTok{## DPG}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir04_DPG.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_trigram %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"DPG"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()}
  
\CommentTok{## OUTROS}
\CommentTok{#jpeg("XX_wordclou_tfidf_dir05_OUTROS.jpeg")}
\NormalTok{set.seed(233115)}
\NormalTok{plot_diretorias_tf_dif_trigram %>%}
\NormalTok{  filter(DIRETORIA == }\StringTok{"OUTROS"}\NormalTok{) %>%}
\NormalTok{  top_n(150, tf_idf) %>%}
\NormalTok{  wordcloud2()  }
\end{Highlighting}
\end{Shaded}

\section{MODELAGEM - APLICAÇÃO E
RESULTADOS}\label{modelagem---aplicacao-e-resultados}

\subsection{Preparação e partição de
dados}\label{preparacao-e-particao-de-dados}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{key_DIR =}\StringTok{ }\NormalTok{plot_diretoria_palavras_noSTOP }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(DIRETORIA) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(DIRETORIA)}

\NormalTok{ key_DIR }\OperatorTok{%>%}
\StringTok{   }\KeywordTok{kable}\NormalTok{(}\StringTok{"latex"}\NormalTok{, }\DataTypeTok{caption =} \StringTok{"Número de termos por diretoria"}\NormalTok{, }
        \DataTypeTok{booktabs =}\NormalTok{ T, }\DataTypeTok{format.args =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{decimal.mark =} \StringTok{','}\NormalTok{, }\DataTypeTok{big.mark =} \StringTok{"."}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\DataTypeTok{latex_options =} \KeywordTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold_position"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]

\caption{\label{tab:unnamed-chunk-73}Número de termos por diretoria}
\centering
\begin{tabular}{lr}
\toprule
DIRETORIA & n\\
\midrule
\rowcolor{gray!6}  DEA & 1.829\\
DEE & 1.921\\
\rowcolor{gray!6}  DGC & 1.507\\
DPG & 408\\
\rowcolor{gray!6}  OUTROS & 348\\
\bottomrule
\end{tabular}
\end{table}

selecionando as 20 palavras mais importantes de cada uma das 4
diretorias e da categoria `OUTROS'.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# plot_diretoria_palavras_noSTOP$palavra <- gsub(".", "_", as.character(plot_diretoria_palavras_noSTOP$palavra))}
\CommentTok{# devo garantir que esses termos sao unicos dentro de cada diretoria}
\CommentTok{# devo, ainda, excluir acentos e pontos e caracteres q nao podem ser inclusos em nomes de variaveis no R}
\CommentTok{# Posteriormente devo refazer esses passos, juntamente com o stemming no arquivo de dados a ser inputado}
\NormalTok{termos_dir =}\StringTok{ }
\NormalTok{plot_diretoria_palavras_noSTOP }\OperatorTok{%>%}
\KeywordTok{group_by}\NormalTok{(DIRETORIA) }\OperatorTok{%>%}
\KeywordTok{top_n}\NormalTok{(}\DecValTok{10}\NormalTok{, tf_idf)}
\end{Highlighting}
\end{Shaded}

Cria, antes, uma variáveil DESCRI\_PEDIDO1 que repete os passos feitos
aos termos quanto ao stemming so que no texto fonte.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO1 =}\StringTok{ }\NormalTok{DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO}
\NormalTok{DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO1 =}\StringTok{ }\KeywordTok{ptstem}\NormalTok{(}\KeywordTok{rslp}\NormalTok{(DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO1))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fe <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\DataTypeTok{data =} \DecValTok{0}\NormalTok{, }\DataTypeTok{nrow =} \KeywordTok{length}\NormalTok{(DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO1), }\DataTypeTok{ncol =} \KeywordTok{length}\NormalTok{(termos_dir}\OperatorTok{$}\NormalTok{palavra))}
\NormalTok{fe <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(fe); }\KeywordTok{colnames}\NormalTok{(fe) <-}\StringTok{ }\NormalTok{termos_dir}\OperatorTok{$}\NormalTok{palavra}

\NormalTok{i=j=}\DecValTok{0}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{length}\NormalTok{(DB}\OperatorTok{$}\NormalTok{ID))\{}
        \ControlFlowTok{for}\NormalTok{(j }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{length}\NormalTok{(termos_dir}\OperatorTok{$}\NormalTok{palavra))\{}
\NormalTok{                g <-}\StringTok{ }\KeywordTok{grepl}\NormalTok{(termos_dir}\OperatorTok{$}\NormalTok{palavra[j], DB}\OperatorTok{$}\NormalTok{DESCRI_PEDIDO1[i])}
                \ControlFlowTok{if}\NormalTok{(g }\OperatorTok{==}\StringTok{ }\OtherTok{TRUE}\NormalTok{)\{}
\NormalTok{                        fe[i, j] <-}\StringTok{ }\DecValTok{1}        
\NormalTok{                \}}
\NormalTok{        \}}
\NormalTok{\}}

\CommentTok{#REMOVE A VARIAVEL geracao que apareceu em deduplicacao}
\NormalTok{fe =}\StringTok{ }\NormalTok{fe[,}\OperatorTok{-}\DecValTok{50}\NormalTok{]}


\NormalTok{termo_dir1 =}\StringTok{ }\NormalTok{termos_dir }\OperatorTok{%>%}
\KeywordTok{select}\NormalTok{(DIRETORIA, palavra) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{termo =}\NormalTok{ palavra)}

\NormalTok{NumTermos =}\StringTok{ }\KeywordTok{as_tibble}\NormalTok{(}\KeywordTok{rbind}\NormalTok{(}\KeywordTok{apply}\NormalTok{(fe,}\DecValTok{2}\NormalTok{,sum)))}
\NormalTok{NumTermos =}\StringTok{ }\KeywordTok{gather}\NormalTok{(NumTermos, }\DataTypeTok{key =} \StringTok{"termo"}\NormalTok{, }\DataTypeTok{value =} \StringTok{"Num_Pedidos"}\NormalTok{)}
\NormalTok{NumTermos =}\StringTok{ }\NormalTok{NumTermos[}\KeywordTok{order}\NormalTok{(NumTermos}\OperatorTok{$}\NormalTok{Num_Pedidos, }\DataTypeTok{decreasing =} \OtherTok{TRUE}\NormalTok{), ]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{highchart() %>%}
\NormalTok{  hc_add_series(data = NumTermos$Num_Pedidos, }
\NormalTok{                type = }\StringTok{"bar"}\NormalTok{,}
\NormalTok{                name = }\StringTok{"# de pedidos"}\NormalTok{,}
\NormalTok{                showInLegend = FALSE,}
\NormalTok{                tooltip = list(valueDecimals = 0, valuePrefix = }\StringTok{""}\NormalTok{, valueSuffix = }\StringTok{""}\NormalTok{), color=}\StringTok{"blue"}\NormalTok{) %>%}
\NormalTok{  hc_yAxis(title = list(text = }\StringTok{"Quantitativo de pedidos"}\NormalTok{), }
\NormalTok{           allowDecimals = TRUE, max = (max(NumTermos$Num_Pedidos)+103),}
\NormalTok{           labels = list(format = }\StringTok{"\{value\}"}\NormalTok{)) %>%}
\NormalTok{  hc_xAxis(title = list(text = }\StringTok{"Termo"}\NormalTok{),}
\NormalTok{           categories = NumTermos$termo,}
\NormalTok{           tickmarkPlacement = }\StringTok{"on"}\NormalTok{,}
\NormalTok{           opposite = FALSE) %>%}
\NormalTok{  hc_title(text = }\StringTok{"Quantitativo de pedidos por termo (sem exclusividade)"}\NormalTok{,}
\NormalTok{           style = list(fontWeight = }\StringTok{"bold"}\NormalTok{)) %>% }
\NormalTok{  hc_subtitle(text = paste(}\StringTok{""}\NormalTok{)) %>%}
\NormalTok{      hc_tooltip(valueDecimals = 2,}
\NormalTok{                 pointFormat = }\StringTok{"\{point.y\} pedidos"}\NormalTok{)%>%}
                 \CommentTok{#pointFormat = "Variável: \{point.x\} <br> Missing: \{point.y\}") }
\NormalTok{      hc_credits(enabled = TRUE, }
                 \FunctionTok{text = "Fonte:}\AttributeTok{ CGU, e-SIC (2019). Elaboração: Ewerson Pimenta.",}
\NormalTok{                 style = list(fontSize = }\StringTok{"10px"}\NormalTok{)) %>%}
\NormalTok{  hc_exporting(enabled = TRUE, filename = }\StringTok{"F3-filmes-genero-Pimenta"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{db_modelo =}\StringTok{ }\KeywordTok{as_tibble}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(}\KeywordTok{select}\NormalTok{(DB,DIRETORIA),fe))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# __Porcentagem de ZEROS por variável__}

\NormalTok{zeros <- (colSums(fe==0)/nrow(fe)*100); var <- names(fe)}
\NormalTok{db_zero <- data.frame(var,zeros); rownames(db_zero) <- NULL}
\NormalTok{db_zero <- db_zero}\KeywordTok{[}\NormalTok{order(db_zero$zeros}\KeywordTok{,}\NormalTok{ decreasing = TRUE)}\KeywordTok{,} \KeywordTok{]}

\NormalTok{hc4_1 <- highchart() %>%}
\NormalTok{  hc_add_series(data = db_zero$zeros, }
\NormalTok{                type = }\StringTok{"bar"}\NormalTok{,}
\NormalTok{                name = }\StringTok{"Porcentagem de zeros"}\NormalTok{,}
\NormalTok{                showInLegend = FALSE,}
\NormalTok{                tooltip = list(valueDecimals = 2, valuePrefix = }\StringTok{""}\NormalTok{, valueSuffix = }\StringTok{" %"}\NormalTok{), color=}\StringTok{"pink"}\NormalTok{) %>%}
\NormalTok{  hc_yAxis(title = list(text = }\StringTok{"Porcentagem de zero"}\NormalTok{), }
\NormalTok{           allowDecimals = TRUE, max = 100,}
\NormalTok{           labels = list(format = }\StringTok{"\{value\}%"}\NormalTok{)) %>%}
\NormalTok{  hc_xAxis(categories = db_zero$var,}
\NormalTok{           tickmarkPlacement = }\StringTok{"on"}\NormalTok{,}
\NormalTok{           opposite = FALSE) %>%}
\NormalTok{  hc_title(text = }\StringTok{"Porcentagem de zeros por variável"}\NormalTok{,}
\NormalTok{           style = list(fontWeight = }\StringTok{"bold"}\NormalTok{)) %>% }
\NormalTok{  hc_subtitle(text = paste(}\StringTok{""}\NormalTok{)) %>%}
\NormalTok{      hc_tooltip(valueDecimals = 2,}
                 \FunctionTok{pointFormat = "Zeros:}\AttributeTok{ }\KeywordTok{\{}\NormalTok{point.y}\KeywordTok{\}}\StringTok{")%>%}
\StringTok{                 #pointFormat = "}\ErrorTok{Variável: \{point.x\} <br> Missing: \{point.y\}") }
\NormalTok{      hc_credits(enabled = TRUE, }
                 \FunctionTok{text = "Fonte:}\AttributeTok{ IMDB/KAGGLE. Elaboração: Ewerson Pimenta.",}
\NormalTok{                 style = list(fontSize = }\StringTok{"10px"}\NormalTok{)) %>%}
\NormalTok{  hc_exporting(enabled = TRUE, filename = }\StringTok{"Fig00-Pimenta"}\NormalTok{)}
\CommentTok{#hc <- hc %>% }
\CommentTok{#  hc_add_theme(hc_theme_darkunica())}
\NormalTok{hc4_1; remove(hc4_1, var, zeros)}
\end{Highlighting}
\end{Shaded}

\subsection{Modelos de classificação}\label{modelos-de-classificacao}

\subsubsection{Partição dos dados}\label{particao-dos-dados}

Particionando a base de dados em Treino e Teste, esses dois (Treino e
Teste) também terão armazenados as diretorias que foram responsaveis por
cada pedido via amostragem probabilística dos dados originais
separadamente das bases de Treino e Teste.

Para amostragem aleatória simples

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{intrain <-}\StringTok{ }\KeywordTok{createDataPartition}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ db_modelo}\OperatorTok{$}\NormalTok{DIRETORIA, }\DataTypeTok{p =} \FloatTok{0.65}\NormalTok{, }\DataTypeTok{list =} \OtherTok{FALSE}\NormalTok{)}
\NormalTok{training <-}\StringTok{ }\NormalTok{db_modelo[intrain,]}
\NormalTok{testing <-}\StringTok{ }\NormalTok{db_modelo[}\OperatorTok{-}\NormalTok{intrain,]}
\end{Highlighting}
\end{Shaded}

\subsubsection{Modelagem 1 - Random Forest
(RF)}\label{modelagem-1---random-forest-rf}

\paragraph{Random Forest (RF) -
Metodologia}\label{random-forest-rf---metodologia}

\textbf{Descrição} 1. Random Forest foi desenvolvido para agregar
árvores de decisão (modelo de classificação);\\
2. Pode ser usado para modelo de classificação (p/ var. resposta
categórica) ou regressão (no caso de haver variável resposta
contínua);\\
3. Evita \emph{overfitting};\\
4. Permite trabalhar com um largo número de características de um
conjunto de dados;\\
5. Auxilia na seleção de variáveis baseada em um algoritmo que calcula a
importância por variável (assim, tendo conhecimento de quais variáveis
são mais importantes, podemos usar essa informação para outros modelos
de classificação);\\
6. User-friendly: apenas 2 parâmetros livres:

\begin{itemize}
\tightlist
\item
  Trees - ntrees, default 500 (Nº de árvores);
\item
  Variáveis selecionadas via amostragem aleatória candidatas à cada
  ``split'' (quebra da árvore) - mtry, default \(\sqrt{p}\) p/
  classificação e \(\frac{p}{3}\) p/ regressão (p: nº de
  features/variáveis);
\end{itemize}

\textbf{Passo-a-Passo}

É realizado em 3 passos:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Desenha as amostras via bootstrap do número de árvores
  \emph{ntrees};\\
\item
  Para cada amostra via bootstrap, cresce o número de árvores
  ``un-puned'' para a escolha da melhor quebra da árvore baseado na
  amostra aleatória do valor predito de mtry a cada nó da árvore;\\
\end{enumerate}

\begin{itemize}
\item
  \begin{enumerate}
  \def\labelenumi{\arabic{enumi}.}
  \setcounter{enumi}{2}
  \tightlist
  \item
    Faz classificação de novos valores usando a maioria de votos p/
    classificação e usa a média p/ regressão baseada nas amostras de
    ntrees.
  \end{enumerate}
\end{itemize}

\paragraph{Random Forest - Aplicação e
Resultados}\label{random-forest---aplicacao-e-resultados}

Inicialmente utilizaremos o pacote \texttt{randomForest} que implmenta o
algoritmo de Random Forest de Breiman (baseado na clusterização de
Breiman, originalmente codificada em Fortran) que tem por finalidade
classificar e/ou criar regressão. Além disso, pode ser usado em um
modelo não supervisionado para avaliar proximidades entre pontos.

Estamos usando, a partir daqui, a base de treino.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#library(randomForest)}
\CommentTok{#library(rpart)}
\CommentTok{#library(rpart.plot)}
\CommentTok{#rf <- randomForest(proximity = T,ntree = 38,do.trace = T,WR~.,data=training)}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{9984512}\NormalTok{)}
\CommentTok{# Training with classification tree}
\NormalTok{rf <-}\StringTok{ }\KeywordTok{rpart}\NormalTok{(DIRETORIA }\OperatorTok{~}\StringTok{ }\NormalTok{., }\DataTypeTok{data=}\NormalTok{training, }\DataTypeTok{method=}\StringTok{"class"}\NormalTok{, }\DataTypeTok{xval =} \DecValTok{4}\NormalTok{)}
\KeywordTok{print}\NormalTok{(rf, }\DataTypeTok{digits =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## n= 369 
## 
## node), split, n, loss, yval, (yprob)
##       * denotes terminal node
## 
##  1) root 369 232 DEA (0.37 0.35 0.2 0.043 0.035)  
##    2) consumo>=0.5 72   8 DEA (0.89 0.083 0 0.014 0.014) *
##    3) consumo< 0.5 297 175 DEE (0.25 0.41 0.25 0.051 0.04)  
##      6) concurso< 0.5 285 163 DEE (0.26 0.43 0.22 0.053 0.042)  
##       12) interna< 0.5 271 149 DEE (0.27 0.45 0.19 0.055 0.037) *
##       13) interna>=0.5 14   3 DGC (0.071 0 0.79 0 0.14) *
##      7) concurso>=0.5 12   0 DGC (0 0 1 0 0) *
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{attributes}\NormalTok{(rf)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $names
##  [1] "frame"               "where"               "call"               
##  [4] "terms"               "cptable"             "method"             
##  [7] "parms"               "control"             "functions"          
## [10] "numresp"             "splits"              "variable.importance"
## [13] "y"                   "ordered"            
## 
## $xlevels
## named list()
## 
## $ylevels
## [1] "DEA"    "DEE"    "DGC"    "DPG"    "OUTROS"
## 
## $class
## [1] "rpart"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Predict the testing set with the trained model }
\NormalTok{predictions1 <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(rf, testing, }\DataTypeTok{type =} \StringTok{"class"}\NormalTok{)}

\CommentTok{# Accuracy and other metrics}
\KeywordTok{confusionMatrix}\NormalTok{(predictions1, }\KeywordTok{as.factor}\NormalTok{(testing}\OperatorTok{$}\NormalTok{DIRETORIA))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction DEA DEE DGC DPG OUTROS
##     DEA     27   2   0   0      0
##     DEE     44  65  30   8      6
##     DGC      2   1  10   0      1
##     DPG      0   0   0   0      0
##     OUTROS   0   0   0   0      0
## 
## Overall Statistics
##                                           
##                Accuracy : 0.5204          
##                  95% CI : (0.4481, 0.5921)
##     No Information Rate : 0.3724          
##     P-Value [Acc > NIR] : 1.747e-05       
##                                           
##                   Kappa : 0.2728          
##  Mcnemar's Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: DEA Class: DEE Class: DGC Class: DPG
## Sensitivity              0.3699     0.9559    0.25000    0.00000
## Specificity              0.9837     0.3125    0.97436    1.00000
## Pos Pred Value           0.9310     0.4248    0.71429        NaN
## Neg Pred Value           0.7246     0.9302    0.83516    0.95918
## Prevalence               0.3724     0.3469    0.20408    0.04082
## Detection Rate           0.1378     0.3316    0.05102    0.00000
## Detection Prevalence     0.1480     0.7806    0.07143    0.00000
## Balanced Accuracy        0.6768     0.6342    0.61218    0.50000
##                      Class: OUTROS
## Sensitivity                0.00000
## Specificity                1.00000
## Pos Pred Value                 NaN
## Neg Pred Value             0.96429
## Prevalence                 0.03571
## Detection Rate             0.00000
## Detection Prevalence       0.00000
## Balanced Accuracy          0.50000
\end{verbatim}

Olhando as 6 primeiras observações real X predito

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1 <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(rf,training)}
\KeywordTok{head}\NormalTok{(p1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         DEA        DEE       DGC        DPG     OUTROS
## 1 0.8888889 0.08333333 0.0000000 0.01388889 0.01388889
## 2 0.8888889 0.08333333 0.0000000 0.01388889 0.01388889
## 3 0.2656827 0.45018450 0.1918819 0.05535055 0.03690037
## 4 0.8888889 0.08333333 0.0000000 0.01388889 0.01388889
## 5 0.2656827 0.45018450 0.1918819 0.05535055 0.03690037
## 6 0.8888889 0.08333333 0.0000000 0.01388889 0.01388889
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(training}\OperatorTok{$}\NormalTok{DIRETORIA)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "DEA" "DEA" "DEA" "DEE" "DEA" "DEA"
\end{verbatim}

Selecionando uma árvore

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rp <-}\StringTok{ }\NormalTok{rpart}\OperatorTok{::}\KeywordTok{rpart}\NormalTok{(}\DataTypeTok{formula =}\NormalTok{ DIRETORIA}\OperatorTok{~}\NormalTok{.,}\DataTypeTok{data=}\NormalTok{training)}
\CommentTok{#rpart::plotcp(rp)}
\KeywordTok{rpart.plot}\NormalTok{(rp)}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-84-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rpart.plot.version1}\NormalTok{(rp)}
\end{Highlighting}
\end{Shaded}

\includegraphics{markdown_v31_files/figure-latex/unnamed-chunk-84-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{set.seed(09986755)}
\NormalTok{rf1 <- randomForest(DIRETORIA ~ ., data=training,}
\NormalTok{                    importance = TRUE,}
\NormalTok{                    proximity = TRUE)}
\end{Highlighting}
\end{Shaded}

\subparagraph{Tuning do modelo}\label{tuning-do-modelo}

a partir de n = 200 árvores o erro OOB tende a estabilizar

Aparentemente mtry = 30 é um bom palpite

Reescrevendo, então, o modelo


\end{document}
