---
title: "Mineração de texto em pedidos de Lei de Acesso à informação - LAI"
output: 
  pdf_document: 
    keep_tex: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 <!-- REFERÊNCIAS
 https://www.tidytextmining.com/tidytext.html#contrasting-tidy-text-with-other-data-structures
 
 -->

## Packages for this routine
```{r, include=FALSE, message=FALSE}
# install.packages("readODS")
library(readODS)        # read .ods file
library(tidyverse)      # data manipulation tidyverse_packages()
library(tidytext)       # Text Mining using 'dplyr', 'ggplot2', and other Tidy Tools
library(tidyr)          # Easily Tidy Data with 'spread()' and 'gather()' Functions
library(tm)
library(quanteda)
library(stringr)
library(knitr)
library(kableExtra)
library(scales)
library(wordcloud)
library(wordcloud2)
```

# BASE DE DADOS

## Importação dos dados
<!--
PATH = "C:/proj_eSIC_v10/textmining_pt/DATA/"
#PATH = "/Users/ewersonpimenta/Desktop/ESIC_TCC/Pedidos_LAI_EPE/BASE_DADOS/"
-->
```{r, include=FALSE, message=FALSE}
#PATH = "C:/proj_eSIC_v10/textmining_pt/DATA/"
PATH = "/Users/ewersonpimenta/Desktop/ESIC_TCC/TCC_v2.1/RMARKDOWN/"
```

Caminho do projeto
```yaml
PATH = "..;/proj_eSIC_v10/textmining_pt/DATA/"
```

```{r child = '01_importacao.Rmd'}
```



- Anexo 02: Tabela - Dicionário de variáveis da tabela de pedidos
```{r}
dic_pedidos %>%
kable("latex", caption = "Dicionário de variáveis da tabela de pedidos", booktabs = T) %>%
  kable_styling(latex_options = c("striped", "hold_position"), full_width = F) %>%
  #column_spec(1:1, width = "3cm") %>%
  column_spec(2:2, width = "15cm") %>%
landscape()
```

- Anexo 03: Tabela - Dicionário de variáveis da tabela de recursos
```{r}
dic_recursos %>%
kable("latex", caption = "Dicionário de variáveis da tabela de recursos", booktabs = T) %>%
  kable_styling(latex_options = c("striped", "hold_position"), full_width = F) %>%
  #column_spec(1:1, width = "3cm") %>%
  column_spec(2:2, width = "15cm") %>%
landscape()
```

- Anexo 04: Tabela - Dicionário de variáveis da tabela de solicitantes
```{r}
dic_solicitantes %>%
kable("latex", caption = "Dicionário de variáveis da tabela de solicitantes", booktabs = T) %>%
  kable_styling(latex_options = c("striped", "hold_position"), full_width = F) %>%
  #column_spec(1:1, width = "3cm") %>%
  column_spec(2:2, width = "15cm") %>%
landscape()
```
